### ISSUE TITLE
Cannot create account

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [owncloud/mail#829] opened 2015-06-29 05:11 UTC
Hi,
I cannot seem to set up my imap account manually. It is hosted on my own server (actually the same machine that runs owncloud). The domain used by the email adress is not the address of the server. When I fill out all the required details, the mail plug-in still seems to try an automatic setup according to the logfile output. When I click to save the settings, I get a yellow toast message at the top stating [object Object].

What am I doing wrong? The mail plugin seems to ignore my manual input and try a generic mailserver adress according to my mail adress format.

The logfile output is:
( I anonymized the log, "username" is my owncloud login which is the same as the part before the @ in my email address, "domain.tld" stands for my domain, but is not the server's address. The "imap.domain.tld" must be generated by the mail app, trying to autodetect the setup. And in spite of what is stated in the log, I did provide a password.)

	Info 	mail 	Auto detect failed 	2015-06-28T17:44:46+02:00
	Info 	mail 	setting up auto detected account 	2015-06-28T17:44:45+02:00
	Info 	mail 	Auto detect failed 	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, imap.domain.tld, 993, username@domain.tld, -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, imap.domain.tld, 993, username, -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, imap.domain.tld, 993, username@domain.tld, tls -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, imap.domain.tld, 993, username, tls -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, imap.domain.tld, 993, username@domain.tld, ssl -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, imap.domain.tld, 993, username, ssl -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, imap.domain.tld, 143, username@domain.tld, -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, imap.domain.tld, 143, username, -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, imap.domain.tld, 143, username@domain.tld, tls -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, imap.domain.tld, 143, username, tls -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, imap.domain.tld, 143, username@domain.tld, ssl -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, imap.domain.tld, 143, username, ssl -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, domain.tld, 993, username@domain.tld, -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, domain.tld, 993, username, -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, domain.tld, 993, username@domain.tld, tls -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, domain.tld, 993, username, tls -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, domain.tld, 993, username@domain.tld, ssl -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, domain.tld, 993, username, ssl -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, domain.tld, 143, username@domain.tld, -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, domain.tld, 143, username, -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, domain.tld, 143, username@domain.tld, tls -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, domain.tld, 143, username, tls -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, domain.tld, 143, username@domain.tld, ssl -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, domain.tld, 143, username, ssl -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, imap.mx.domain.tld, 993, username@domain.tld, -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, imap.mx.domain.tld, 993, username, -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, imap.mx.domain.tld, 993, username@domain.tld, tls -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, imap.mx.domain.tld, 993, username, tls -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, imap.mx.domain.tld, 993, username@domain.tld, ssl -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, imap.mx.domain.tld, 993, username, ssl -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, domain.tld, 143, username@domain.tld, tls -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, domain.tld, 143, username, tls -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, domain.tld, 143, username@domain.tld, ssl -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, domain.tld, 143, username, ssl -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, imap.mx.domain.tld, 993, username@domain.tld, -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, imap.mx.domain.tld, 993, username, -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, imap.mx.domain.tld, 993, username@domain.tld, tls -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, imap.mx.domain.tld, 993, username, tls -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, imap.mx.domain.tld, 993, username@domain.tld, ssl -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, imap.mx.domain.tld, 993, username, ssl -> No password provided.	2015-06-28T17:40:10+02:00
	Info	mail	Test-Account-Failed: username, imap.mx.domain.tld, 143, username@domain.tld, -> No password provided.	2015-06-28T17:40:09+02:00
	Info	mail	Test-Account-Failed: username, imap.mx.domain.tld, 143, username, -> No password provided.	2015-06-28T17:40:09+02:00
	Info	mail	Test-Account-Failed: username, imap.mx.domain.tld, 143, username@domain.tld, tls -> No password provided.	2015-06-28T17:40:09+02:00
	Info	mail	Test-Account-Failed: username, imap.mx.domain.tld, 143, username, tls -> No password provided.	2015-06-28T17:40:09+02:00
	Info	mail	Test-Account-Failed: username, imap.mx.domain.tld, 143, username@domain.tld, ssl -> No password provided.	2015-06-28T17:40:09+02:00
	Info	mail	Test-Account-Failed: username, imap.mx.domain.tld, 143, username, ssl -> No password provided.	2015-06-28T17:40:09+02:00
	Info	mail	Test-Account-Failed: username, mx.domain.tld, 993, username@domain.tld, -> No password provided.	2015-06-28T17:40:09+02:00
	Info	mail	Test-Account-Failed: username, mx.domain.tld, 993, username, -> No password provided.	2015-06-28T17:40:09+02:00
	Info	mail	Test-Account-Failed: username, mx.domain.tld, 993, username@domain.tld, tls -> No password provided.	2015-06-28T17:40:09+02:00
	Info	mail	Test-Account-Failed: username, mx.domain.tld, 993, username, tls -> No password provided.	2015-06-28T17:40:09+02:00

**Comment by ChristophWurst** [comment] 2015-06-29 07:04
duplicate of #813

**Closed by ChristophWurst** 2015-06-29 07:04 UTC

**Comment by 1337sup3rh4x0r** [comment] 2015-06-29 07:35
Thank you, changing the mentioned line in the file worked for me!
