### ISSUE TITLE
Sending email with very long history

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/mail#1252] opened 2016-02-01 08:01 UTC
The "send" button is on the bottom of the email edit field.
If the email contains a very long history the user has to scroll a very long way to send the mail.
(never tried if ctrl + enter is working).
The best would be that the send button is always visible, snapped to the bottom edge of the browser.

**Comment by ChristophWurst** [comment] 2016-02-01 08:21
cc @jancborchardt

**Comment by jancborchardt** [comment] 2016-02-17 18:04
This is basically a duplicate of https://github.com/owncloud/mail/issues/900 – and I’m working on it right now. :)

**Closed by jancborchardt** 2016-02-17 18:04 UTC
Labels: 1 - to develop, enhancement
