### ISSUE TITLE
Request - separate reply view from mail view

### ISSUE THREAD

**Issue by itheiss** [owncloud/mail#1045] opened 2015-09-04 12:11 UTC
I would suggest putting the message view (reading mail) and the reply view in separate views. Here are some screens from RainLoop Webmail for reference. 

**Message view**

With button for reply and an additional drop-down menu ...

![message_view](https://cloud.githubusercontent.com/assets/2655169/9683100/2534d872-530d-11e5-95da-2c7c3241e864.jpg)

**Reply view**

First screen the message editor is open ...

![reply_view_message](https://cloud.githubusercontent.com/assets/2655169/9683123/5d54b3ee-530d-11e5-8a39-2f72a68e97ca.jpg)

Second screen the attachment  management is open. Here the user could see preview of the attachments, add or delete attachments. We could add a drop zone here once local attachments are ready, etc...

![reply_view_attachment](https://cloud.githubusercontent.com/assets/2655169/9683124/601e2f88-530d-11e5-81b0-bb07152f3203.jpg)

I think this is usefull for some of the upcoming features (block images, local attachments, html editor, etc.). Any thought on this?

Regards
Ingo

**Comment by jancborchardt** [comment] 2015-09-04 12:14
@itheiss which are the concrete problems you have with the current layout & interaction? Then we can see how to improve it. :)

**Comment by itheiss** [comment] 2015-09-04 12:42
@jancborchardt Not really a problem :-) The current mixed up message and reply view just feel a bit like a draft or "unfinished". Or maybe I just haven't seen any mail client where you can directly reply without hitting a reply or forward button :-))

I am not really I design or usability master but the example screens I uploaded just feel more tidily. The buttons for interaction are placed all in the upper head and not cluttered all over.

![current_view](https://cloud.githubusercontent.com/assets/2655169/9683725/ff44a146-5312-11e5-93a2-93b2a80e6451.jpg)

Please don't get me wrong this is no personal criticism. You all do a fantastic job!!!

**Comment by jancborchardt** [comment] 2015-09-07 08:27
Yeah, the buttons are all over the place right now, that’s correct and I want to change that.

The reply form is directly there so it’s possible to reply very fast without additional interaction.

**Comment by jancborchardt** [comment] 2015-09-16 21:58
The reply button position was fixed with https://github.com/owncloud/mail/pull/1094, the rest is a duplicate of https://github.com/owncloud/mail/issues/900

**Closed by jancborchardt** 2015-09-16 21:58 UTC
Labels: 1 - to develop, discussion, enhancement
