### ISSUE TITLE
ownCloud 9: error while loading messages

### ISSUE THREAD

**Issue by BenS89** [owncloud/mail#1337] opened 2016-03-10 12:10 UTC
### Steps to reproduce
1. Upgrade from 8.2.2 to 9.0
2. Apply [#23056](https://github.com/owncloud/core/pull/23056) (fix for [#23044](https://github.com/owncloud/core/issues/23044)) and [#23016](https://github.com/owncloud/core/pull/23016) (fix for [#22997](https://github.com/owncloud/core/issues/22997)) 
3. Open your Mail inbox 

### Expected behaviour
Your mail inbox is loaded (like it does in 8.2.2)

### Actual behaviour
The following error is shown: "Error while loading messages"
In the logs, you can see: <code>{"reqId":"DE4ggOJEAcsgJD5ufbMI","remoteAddr":"192.168.2.113","app":"index","message":"Exception: ","level":3,"time":"2016-03-10T11:13:18+00:00"}
</code> 

**OwnCloud Mail version:** (see ownCloud apps admin page)  0.3.0

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...) iCloud

**Number of accounts:** 1

### Server configuration
**Operating system**: Qnap Embedded Linux

**Web server:** Apache 2.4.12

**Database:** MariaDB 5.5

**PHP version:** 5.6

**ownCloud version:** (see ownCloud admin page) 9.0

**Updated from an older ownCloud or fresh install:** yes, from 8.2.2

**List of activated apps:** Calendar 1.0, Contacts 1.0, Mail 0.3.0

**Comment by ChristophWurst** [comment] 2016-03-10 12:17
Hi @BenS89!
Please [enable debug mode](https://doc.owncloud.org/server/9.0/developer_manual/general/devenv.html#enabling-debug-mode) and post your owncloud.log and horde.log. Thanks.

**Comment by BenS89** [comment] 2016-03-10 12:30
owncloud log says:

<code>{"reqId":"DFhlTHH0fkUbA+bqzryt","remoteAddr":"192.168.2.113","app":"mail","message":"loading messages 0 to 20 of folder <SU5CT1g=>","level":0,"time":"2016-03-10T12:24:25+00:00","method":"GET","url":"\/owncloud\/apps\/mail\/accounts\/1\/folders\/SU5CT1g%3D\/messages"}

{"reqId":"DFhlTHH0fkUbA+bqzryt","remoteAddr":"192.168.2.113","app":"index","message":"Exception: ","level":3,"time":"2016-03-10T12:24:25+00:00","method":"GET","url":"\/owncloud\/apps\/mail\/accounts\/1\/folders\/SU5CT1g%3D\/messages"}
</code>

horde.log says:

<code>------------------------------
>> Thu, 10 Mar 2016 12:28:25 +0000
>> Connection to: imap://imap.mail.me.com:993/
>> Server connection took 0.3823 seconds.
S: * OK [CAPABILITY st11p00mm-iscream007 15E205 XAPPLEPUSHSERVICE IMAP4 IMAP4rev1 SASL-IR AUTH=ATOKEN AUTH=PLAIN] iSCREAM ready to rumble (15E205-0982aaf890fd:3979) st11p00mm-iscream007 [28:1012:12:28:25:69]
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: xxxxx)]
S: 1 OK [CAPABILITY XAPPLEPUSHSERVICE IMAP4 IMAP4rev1 ACL RIGHTS=tekx QUOTA LITERAL+ NAMESPACE UIDPLUS CHILDREN BINARY UNSELECT SORT CATENATE URLAUTH LANGUAGE ESEARCH ESORT THREAD=ORDEREDSUBJECT THREAD=REFERENCES CONDSTORE ENABLE QRESYNC CONTEXT=SEARCH CONTEXT=SORT WITHIN SASL-IR SEARCHRES METADATA ID XSENDER X-SUN-SORT ANNOTATE-EXPERIMENT-1 X-UNAUTHENTICATE X-SUN-IMAP XUM1 IDLE] User ben.schnarr logged in
>> Command 1 took 0.1357 seconds.
>> CACHE: Using the OCA\Mail\Cache\Cache storage driver.
C: 2 ENABLE QRESYNC
C: 3 LIST "" *
S: * ENABLED QRESYNC
S: 2 OK Completed
>> Command 2 took 0.1154 seconds.
S: * LIST (\NoInferiors) "/" INBOX
S: * LIST (\HasNoChildren) "/" Archive
S: * LIST (\HasNoChildren) "/" "Deleted Messages"
S: * LIST (\HasNoChildren) "/" Drafts
S: * LIST (\HasNoChildren) "/" Junk
S: * LIST (\HasNoChildren) "/" Junk-E-Mail
S: * LIST (\HasNoChildren) "/" Notes
S: * LIST (\HasNoChildren) "/" Sent
S: * LIST (\HasNoChildren) "/" "Sent Messages"
S: * LIST (\HasNoChildren) "/" Trash
S: 3 OK Completed
>> Command 3 took 0.2351 seconds.
C: 4 STATUS Sent (MESSAGES)
S: * STATUS Sent (MESSAGES 0)
S: 4 OK Completed
>> Command 4 took 0.1165 seconds.
C: 5 STATUS Sent (MESSAGES)
S: * STATUS Sent (MESSAGES 0)
S: 5 OK Completed
>> Command 5 took 0.1164 seconds.
C: 6 STATUS "Sent Messages" (MESSAGES)
S: * STATUS "Sent Messages" (MESSAGES 504)
S: 6 OK Completed
>> Command 6 took 0.1288 seconds.
C: 7 STATUS "Sent Messages" (MESSAGES)
S: * STATUS "Sent Messages" (MESSAGES 504)
S: 7 OK Completed
>> Command 7 took 0.2625 seconds.
C: 8 STATUS "Deleted Messages" (MESSAGES)
S: * STATUS "Deleted Messages" (MESSAGES 53)
S: 8 OK Completed
>> Command 8 took 0.1704 seconds.
C: 9 STATUS "Deleted Messages" (MESSAGES)
S: * STATUS "Deleted Messages" (MESSAGES 53)
S: 9 OK Completed
>> Command 9 took 0.1159 seconds.
C: 10 STATUS Trash (MESSAGES)
S: * STATUS Trash (MESSAGES 0)
S: 10 OK Completed
>> Command 10 took 0.1241 seconds.
C: 11 STATUS INBOX (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 12 STATUS Drafts (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 13 STATUS Sent (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 14 STATUS "Sent Messages" (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 15 STATUS Archive (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 16 STATUS Junk (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 17 STATUS "Deleted Messages" (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 18 STATUS Trash (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 19 STATUS Junk-E-Mail (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 20 STATUS Notes (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
S: * STATUS INBOX (MESSAGES 498 RECENT 0 UIDNEXT 10821 UIDVALIDITY 1319235664 UNSEEN 1)
S: 11 OK Completed
>> Command 11 took 0.1182 seconds.
S: * STATUS Drafts (MESSAGES 2 RECENT 0 UIDNEXT 7945 UIDVALIDITY 1319237005 UNSEEN 0)
S: 12 OK Completed
>> Command 12 took 0.2405 seconds.
S: * STATUS Sent (MESSAGES 0 RECENT 0 UIDNEXT 20 UIDVALIDITY 1320076264 UNSEEN 0)
S: 13 OK Completed
>> Command 13 took 0.3936 seconds.
S: * STATUS "Sent Messages" (MESSAGES 504 RECENT 0 UIDNEXT 1287 UIDVALIDITY 1319237005 UNSEEN 0)
S: 14 OK Completed
>> Command 14 took 0.3944 seconds.
S: * STATUS Archive (MESSAGES 21 RECENT 0 UIDNEXT 63 UIDVALIDITY 1319237005 UNSEEN 0)
S: 15 OK Completed
>> Command 15 took 0.3948 seconds.
S: * STATUS Junk (MESSAGES 0 RECENT 0 UIDNEXT 46 UIDVALIDITY 1319237005 UNSEEN 0)
S: 16 OK Completed
>> Command 16 took 0.3955 seconds.
S: * STATUS "Deleted Messages" (MESSAGES 53 RECENT 0 UIDNEXT 11213 UIDVALIDITY 1319236613 UNSEEN 0)
S: 17 OK Completed
>> Command 17 took 0.3965 seconds.
S: * STATUS Trash (MESSAGES 0 RECENT 0 UIDNEXT 54 UIDVALIDITY 1319463752 UNSEEN 0)
S: 18 OK Completed
>> Command 18 took 0.397 seconds.
S: * STATUS Junk-E-Mail (MESSAGES 0 RECENT 0 UIDNEXT 1 UIDVALIDITY 1319236134 UNSEEN 0)
S: 19 OK Completed
>> Command 19 took 0.3978 seconds.
S: * STATUS Notes (MESSAGES 26 RECENT 0 UIDNEXT 2722 UIDVALIDITY 1326749272 UNSEEN 1)
S: 20 OK Completed
>> Command 20 took 0.3985 seconds.
C: 21 STATUS INBOX (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
S: * STATUS INBOX (MESSAGES 498 RECENT 0 UIDNEXT 10821 UIDVALIDITY 1319235664 UNSEEN 1)
S: 21 OK Completed
>> Command 21 took 0.1169 seconds.
C: 22 STATUS Sent (MESSAGES)
S: * STATUS Sent (MESSAGES 0)
S: 22 OK Completed
>> Command 22 took 0.1164 seconds.
C: 23 STATUS Sent (MESSAGES)
S: * STATUS Sent (MESSAGES 0)
S: 23 OK Completed
>> Command 23 took 0.1164 seconds.
C: 24 STATUS "Sent Messages" (MESSAGES)
S: * STATUS "Sent Messages" (MESSAGES 504)
S: 24 OK Completed
>> Command 24 took 0.1164 seconds.
C: 25 STATUS "Sent Messages" (MESSAGES)
S: * STATUS "Sent Messages" (MESSAGES 504)
S: 25 OK Completed
>> Command 25 took 0.116 seconds.
C: 26 STATUS "Deleted Messages" (MESSAGES)
S: * STATUS "Deleted Messages" (MESSAGES 53)
S: 26 OK Completed
>> Command 26 took 0.1165 seconds.
C: 27 STATUS "Deleted Messages" (MESSAGES)
S: * STATUS "Deleted Messages" (MESSAGES 53)
S: 27 OK Completed
>> Command 27 took 0.1173 seconds.
C: 28 STATUS Trash (MESSAGES)
S: * STATUS Trash (MESSAGES 0)
S: 28 OK Completed
>> Command 28 took 0.1166 seconds.
C: 29 LOGOUT
S: * BYE LOGOUT received
S: 29 OK Completed
>> Command 29 took 0.1148 seconds.
------------------------------
>> Thu, 10 Mar 2016 12:28:28 +0000
>> Connection to: imap://imap.mail.me.com:993/
>> Server connection took 0.3608 seconds.
S: * OK [CAPABILITY st11p00mm-iscream033 15E205 XAPPLEPUSHSERVICE IMAP4 IMAP4rev1 SASL-IR AUTH=ATOKEN AUTH=PLAIN] iSCREAM ready to rumble (15E205-0982aaf890fd:19377) st11p00mm-iscream033 [16:72:12:28:28:DA]
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: ben.schnarr)]
S: 1 OK [CAPABILITY XAPPLEPUSHSERVICE IMAP4 IMAP4rev1 ACL RIGHTS=tekx QUOTA LITERAL+ NAMESPACE UIDPLUS CHILDREN BINARY UNSELECT SORT CATENATE URLAUTH LANGUAGE ESEARCH ESORT THREAD=ORDEREDSUBJECT THREAD=REFERENCES CONDSTORE ENABLE QRESYNC CONTEXT=SEARCH CONTEXT=SORT WITHIN SASL-IR SEARCHRES METADATA ID XSENDER X-SUN-SORT ANNOTATE-EXPERIMENT-1 X-UNAUTHENTICATE X-SUN-IMAP XUM1 IDLE] User ben.schnarr logged in
>> Command 1 took 0.1342 seconds.
>> CACHE: Using the OCA\Mail\Cache\Cache storage driver.
C: 2 ENABLE QRESYNC
C: 3 EXAMINE INBOX (QRESYNC (1319235664 295273127139138 10659,10720,10725,10734:10736,10739,10741,10743:10744,10752,10764:10766,10769,10771,10774:10775,10779,10789:10790,10804,10808,10811:10812,10814,10817:10820))
S: * ENABLED QRESYNC
S: 2 OK Completed
>> Command 2 took 0.1151 seconds.
S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen NotJunk $NotJunk JunkRecorded $Junk $Forwarded)
S: * OK [PERMANENTFLAGS ()]
S: * 498 EXISTS
S: * 0 RECENT
S: * OK [UNSEEN 498]
S: * OK [UIDVALIDITY 1319235664]
S: * OK [UIDNEXT 10821]
S: * OK [HIGHESTMODSEQ 295273127139138]
S: 3 OK [READ-ONLY] Completed
>> Command 3 took 0.2332 seconds.
>> SEARCH: Retrieved search from cache (2f23fbf237df415917ad11c3f4276da0 [INBOX])
>> CACHE: Retrieved messages (HICenv,HICflags,HIChdrs,HICdate,HICsize,HICstruct,HICdg [INBOX; 10744,10752,10764:10766,10769,10771,10774:10775,10779,10789:10790,10804,10808,10811:10812,10814,10817:10820])
C: 4 LOGOUT
S: * BYE LOGOUT received
S: 4 OK Completed
>> Command 4 took 0.1148 seconds.
</code>

**Comment by ChristophWurst** [comment] 2016-03-10 12:54
cc @owncloud/mail

**Comment by BenS89** [comment] 2016-03-10 16:15
I recognized that there is no **accounts**-folder under owncloud/apps/mail. Therefore, the url request <code>\/owncloud\/apps\/mail\/accounts\/1\/folders\/SU5CT1g%3D\/messages"}</code> goes into the empty. I reinstalled the whole app without success. I deleted my Mail account and created a new one. Also without success.

**Comment by ChristophWurst** [comment] 2016-03-10 16:28
@BenS89 that is intended. That URL is mapped according to the [routes](https://github.com/owncloud/mail/blob/master/appinfo/routes.php#L64) files, it doesn't exist physically.

**Comment by joergmschulz** [comment] 2016-03-11 07:34
When I add access to the same mailbox from a fresh account, it seems to work. So, maybe some cache issues? How can I clear / remove caches?

**Comment by BenS89** [comment] 2016-03-11 08:28
Disabling the server-side caching with <code>'app.mail.server-side-cache.enabled' => false</code> did not work for me.

**Comment by Echse27** [comment] 2016-03-11 12:30
Loading Mail from an existing mail account in OC8.2.2 was successfull every time.
Now, after update to OC9.0.0 no mails shown.
After complete reinstalling the mail app the problem also present.
Is there a workaround or fix?

**Comment by coderonline** [comment] 2016-03-11 12:52
confirmed. same here.

**Comment by ChristophWurst** [comment] 2016-03-11 14:03
> When I add access to the same mailbox from a fresh account, it seems to work. So, maybe some cache issues? How can I clear / remove caches?

@joergmschulz client-side cache can be cleared by running ```localstorage.clear()``` in your browser's console.

**Comment by joergmschulz** [comment] 2016-03-11 14:22
This helps. Obviously, this should have been done on upgrade for all users.

**Comment by ChristophWurst** [comment] 2016-03-11 14:42
> This helps. Obviously, this should have been done on upgrade for all users.

https://github.com/owncloud/mail/issues/965 ;-)

**Comment by ChristophWurst** [comment] 2016-03-11 15:26
@Echse27 please open a separate issue as the those bugs are unrelated. Thx

**Comment by ChristophWurst** [comment] 2016-03-11 15:29
@BenS89 @joergmschulz is this problem solved by clearing the cache? Then please close it and we'll continue in #965. Thanks you.

**Comment by ChristophWurst** [comment] 2016-03-11 15:31
Since it makes no sense to me why the client-side cache would need to be cleared when the owncloud core is upgraded – did you have mail 0.3 before or did you install it via the owncloud core update?

**Comment by ChristophWurst** [comment] 2016-03-11 15:33
> confirmed. same here.
> also it seems to make a different whether or not the mail sender is in the address book

@coderonline please open an issue for that. This seems to be unrelated to this bug. Probably contact image urls (which are cached client-side) have changed due to the new contacts up and that may lead to browser errors.

**Comment by BenS89** [comment] 2016-03-11 19:48
<code>localstorage.clear()</code> in the Chrome Console gives me <code>Uncaught ReferenceError: localstorage is not defined(…)</code>

**Comment by BenS89** [comment] 2016-03-11 19:50
<code>localstorage.clear</code> did not solve this issue.

**Comment by joergmschulz** [comment] 2016-03-11 21:30
@ChristophWurst: For me, it DID resolve the issue. 
By the way: localStorage (capital S). I did it using Apple/Safari.

**Comment by ChristophWurst** [comment] 2016-03-12 08:01
> Since it makes no sense to me why the client-side cache would need to be cleared when the owncloud core is upgraded – did you have mail 0.3 before or did you install it via the owncloud core update?

@BenS89 ^

**Comment by BenS89** [comment] 2016-03-12 09:13
I had mail 0.3.0 before with 8.2.2. I disabled the app and upgraded to 9.0

**Comment by ChristophWurst** [comment] 2016-03-12 09:35
@BenS89 ok thanks for providing that information. Could you please try to reproduce that in a clean environment? E.g. set up owncloud 8.2 in a VM, install mail 0.3 from the app store and configure your account(s). Once everything is set up, upgrade to owncloud 9.

Otherwise there's no way for me to reproduce or fix this. Apparently the logs tell nothing about the concrete exception that was raised, so I don't even know where to start debugging this…

**Comment by BenS89** [comment] 2016-03-12 13:11
What I did is:

1. Delete the whole Mail account and run 

```sql
DELETE FROM oc_appconfig WHERE appid = 'mail';
DROP TABLE oc_mail_accounts;
```
Without success.

2. Deinstall the whole app and run 

```sql
DELETE FROM oc_appconfig WHERE appid = 'mail';
DROP TABLE oc_mail_accounts;
```

Reinstall it again via App Store. Without success.

It seems that this issue affects only my installation. In case of doubt we could close this issue and I will wait for oc 9.0.1

**Comment by ChristophWurst** [comment] 2016-03-12 13:37
Let's put this on the backlog until someone provides steps to reproduce this issue or useful log entries.

**Comment by Echse27** [comment] 2016-03-12 15:35
Now i have open a new issue #1341

**Comment by ChristophWurst** [comment] 2016-03-16 11:10
I could finally reproduce this on one of my owncloud installation: #1348. Let's continue there.

**Comment by ChristophWurst** [comment] 2016-03-16 21:35
@BenS89 please check whether #1348 fixes your issues

**Comment by BenS89** [comment] 2016-03-16 22:12
@ChristophWurst Unfortunately, I still get the same error, even with #1352. Was worth a try. owncloud.log is nearly saying nothing about it:

<code>{"reqId":"qIKrDgEKNSr3vem7Y8B9","remoteAddr":"192.168.2.113","app":"index","message":"Exception: ","level":3,"time":"2016-03-16T22:09:38+00:00"}</code>

All I can say is that this did not happen with 8.2.2. But since for others worked your fix, maybe it is related to my installation.

**Comment by ChristophWurst** [comment] 2016-03-17 08:45
@BenS89 are you using the contacts app? If yes, which version?

**Comment by BenS89** [comment] 2016-03-17 10:00
@ChristophWurst yes, am using Contacts app version 1.0.0.

**Comment by ChristophWurst** [comment] 2016-03-17 10:30
@BenS89 I found another path that used faulty contact images. Could you please check again if PR #1352 resolves your issue. Thx

**Closed** 2016-03-17 12:10 UTC
Labels: bug, needs info

**Comment by BenS89** [comment] 2016-03-17 20:57
@ChristophWurst #1352 fixed my issue. Very good job! Thank you very much for this!
