### ISSUE TITLE
Make it possible to create filter for incoming messages

### ISSUE THREAD

**Issue by enoch85** [owncloud/mail#661] opened 2015-05-11 21:01 UTC
Would be nice to be able to filter incoming messages, i.e. if I want to filter all the mails from GitHub to a specific folder in my mailbox.

**Comment by jancborchardt** [comment] 2015-05-12 01:03
This is a duplicate of either https://github.com/owncloud/mail/issues/564, https://github.com/owncloud/mail/issues/351, https://github.com/owncloud/mail/issues/57 or https://github.com/owncloud/mail/issues/411 ;)

**Closed by jancborchardt** 2015-05-12 01:03 UTC
Labels: 1 - to develop, enhancement

**Comment by enoch85** [comment] 2015-05-12 08:16
@jancborchardt Sorry for my laziness. ;)
