### ISSUE TITLE
Address autocompletion not working anymore with new Contacts app (regression)

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1388] opened 2016-03-31 08:34 UTC
Any idea bout this @DeepDiver1975 @Henni @ChristophWurst @Gomez?

**Comment by Gomez** [comment] 2016-03-31 09:09
Yes, we know. There was some discussion on the last meetup. @DeepDiver1975 @ChristophWurst You remember, what was it exactly? Something needs to be done in Contacts first? Lets write it down, so we can work on it.

**Comment by ChristophWurst** [comment] 2016-03-31 13:10
This is not a bug with the new contacts app, but rather a problem of this app. Collected addresses are also not completed. Hence, this is a duplicate of #1345

What is broken with the new dav app is the contacts image, but that needs be fixed in core: https://github.com/owncloud/core/issues/23345

**Closed by ChristophWurst** 2016-03-31 13:10 UTC
Labels: 1 - to develop, bug, priority

**Comment by jancborchardt** [comment] 2016-03-31 13:53
Great, ok. Would be really awesome to have this fixed for 0.4.2 :)

**Comment by ChristophWurst** [comment] 2016-03-31 16:40
Sure, PR is welcome :-P

**Comment by jancborchardt** [comment] 2016-03-31 17:09
:D that’s what I’m thinking
