### ISSUE TITLE
Error "String contains non-ASCII characters when sending emails

### ISSUE THREAD

**Issue by farson2003** [owncloud/mail#895] opened 2015-07-21 08:12 UTC
Whenever we send an email we get the message as in screenshot (OC8.1. with Mail 0.2)
![string](https://cloud.githubusercontent.com/assets/3358665/8795867/81a68b3a-2f88-11e5-8bb0-d960795e73bb.png)

**Comment by DeepDiver1975** [comment] 2015-07-21 08:33
Anything in data/owncloud.log?

**Comment by farson2003** [comment] 2015-07-21 09:24
Only:

Error mail Sending mail failed: String contains non-ASCII characters. 2015-07-21T08:09:41+00:00 
Error mail Saving draft failed: String contains non-ASCII characters. 2015-07-21T08:09:34+00:00 
Error PHP Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. at Unknown#0 2015-07-21T08:05:23+00:00 


The last one I think is not relevant to you...

**Comment by DeepDiver1975** [comment] 2015-07-21 13:56
any idea which characters this might be? Any specific charset in place on your system? THX

**Comment by farson2003** [comment] 2015-07-30 21:17
Nothing special on the system!

**Comment by clementhk** [comment] 2015-07-31 00:27
Sounds like a horde mailbox name issue again?

**Comment by clementhk** [comment] 2015-07-31 00:30
Can you turn on debug mode and see what you got?
https://github.com/owncloud/mail#debug-mode

**Comment by xn--nding-jua** [comment] 2015-08-28 12:31
Hey,

I've commented the lines 69 to 76 within the file "apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Data/Format/String.php"

```
        if (isset($this->_filter) &&
            $this->_filter->nonascii &&
            !($this instanceof Horde_Imap_Client_Data_Format_String_Support_Nonascii)) {
            throw new Horde_Imap_Client_Data_Format_Exception(
                'String contains non-ASCII characters.'
            );
        }
```

so no exception is thrown and the original error-message will be shown within the owncloud.log. Then you will see the original message "Sending mail failed: Could not open mailbox "Entw??rfe"."

As I'm using a German backend my "Draft"-folder is called "Entwürfe" and horde does not like this :)

Any suggestions?

**Comment by xn--nding-jua** [comment] 2015-08-28 13:14
I've done some more investigation. The problem occurs in this function-calling:

https://github.com/owncloud/mail/blob/master/lib/controller/accountscontroller.php#L441

Two lines before:
https://github.com/owncloud/mail/blob/master/lib/controller/accountscontroller.php#L439
returns "Entwürfe"

then the function "deleteDraft" is called. There the following line throws the exception:
https://github.com/owncloud/mail/blob/master/lib/account.php#L387


kind regards,
Chris

**Comment by PoPoutdoor** [comment] 2015-08-29 04:39
I think this related to server i18n/L10n support.

FYI: http://www.horde.org/apps/horde/docs/TRANSLATIONS#gnu-gettext-php-and-horde

@farson2003 @xn--nding-jua Please post info about server and web server.

**Comment by farson2003** [comment] 2015-09-05 11:56
We use AllInkl Shared Hosting. PHP 5.6 (CGI)

**Comment by PoPoutdoor** [comment] 2015-09-05 17:02
@farson2003 Can you post output of phpinfo?

**Comment by xn--nding-jua** [comment] 2015-09-05 22:20
@PoPoutdoor 
same here: AllInkl Shared Hosting, but with PHP 5.5.26. The phpinfo() output can be downloaded as html here: https://cloud.noeding-online.de/index.php/s/980778d02538789124278f39f9522d9d/download?path=%2F&files=phpinfo.html

bye,
Chris

**Comment by PoPoutdoor** [comment] 2015-09-06 06:29
@xn--nding-jua phpinfo() seems normal, maybe mail server side issue.

I test with Yahoo account and create a folder name "Entwürfe",  the subfolder shown without related error.

Please try Yahoo and other free mail service to verified this is  web server side issue.

**Comment by PoPoutdoor** [comment] 2015-09-06 10:45
@farson2003 @xn--nding-jua Send/reply mail with Yahoo account from folder "Entwürfe", no error at all.

FYI: Mail App 0.2 / Owncloud 8.1.0

**Comment by xn--nding-jua** [comment] 2015-09-07 10:01
I'm using the mail-backend from AllInkl-Hoster. This is a german hoster and the standard-folders are named "Entwürfe" by default. So there is no "Draft" folder that is renamed to "Entwürfe". There is the original "Entwürfe"-folder that is associated with the "Entwürfe"-folder (see picture attached to this post):


![mailproblem](https://cloud.githubusercontent.com/assets/9845353/9714394/f9535d58-5557-11e5-8f60-65ef7410992f.png)


Maybe this is the origin of the problem. The ownCloud-mail-system asks for the "Draft" folder, AllInkl answers with "Entwürfe" and Horde mixes up the "ü"-characters.

Kind regards,
Chris

**Comment by PoPoutdoor** [comment] 2015-09-07 15:30
@xn--nding-jua Dig up v0.2 code: https://github.com/owncloud/mail/blob/v0.2.0/lib/account.php#L292

My Yahoo account shows 2 "Drafts" folder on Mail app, but a "Draft" (this is the real draft folder) and a "Drafts" folder with desktop mail client.

Do you also have a folder "Drafts" created?

**Comment by xn--nding-jua** [comment] 2015-09-07 15:37
@PoPoutdoor 

no, I've got no "Draft" or "Drafts" folders. Only "Entwüfe". As the received string is "Entwürfe" and converted to "Entw??rfe" the AllInkl-Mailserver translates the "drafts" request to the correct folder. But the oc-mail-app or Horde has a problem with it.

**Comment by ChristophWurst** [comment] 2015-09-07 15:47
@xn--nding-jua could you please enable [imap logging](https://github.com/owncloud/mail#debug-mode) and post your folder's names here. With my german mail account it looks like this:
```
C: 2 LIST "" *
S: * LIST (\HasNoChildren) "." "Junk"
S: * LIST (\HasNoChildren) "." "Sent"
S: * LIST (\HasNoChildren) "." "Entw&APw-rfe"
S: * LIST (\HasNoChildren) "." "Draft"
S: * LIST (\HasNoChildren) "." "Trash"
S: * LIST (\HasNoChildren) "." "INBOX"
S: 2 OK List completed.
```

As you can see, my "Entwürfe" folder is stored as "Entw&APw-rfe".

**Comment by xn--nding-jua** [comment] 2015-09-07 15:52
Hi,

same here:

```
C: 4 LIST () "" (*) RETURN (SPECIAL-USE)
S: * LIST (\NoInferiors \UnMarked \Junk) "/" Spam
S: * LIST (\NoInferiors \UnMarked) "/" Junk-E-Mail
S: * LIST (\NoInferiors \UnMarked) "/" Templates
S: * LIST (\NoInferiors \UnMarked \Drafts) "/" Entw&APw-rfe
S: * LIST (\NoInferiors \UnMarked \Sent) "/" Gesendet
S: * LIST (\NoInferiors \Marked \Trash) "/" Papierkorb
S: * LIST (\NoInferiors \UnMarked) "/" Archives
S: * LIST () "/" INBOX
S: 4 OK List completed (0.000 secs).
```

**Comment by PoPoutdoor** [comment] 2015-09-14 02:52
Does anybody reproduced this with Yahoo account, or with other free webmail services?

**Comment by xn--nding-jua** [comment] 2015-10-14 09:50
I've found a simple workaround for this problem. Simply remove the "->utf8" in the following line: https://github.com/owncloud/mail/blob/master/lib/mailbox.php#L178

No side-effects at the moment. Saving drafts and opening drafts is working and the created drafts are removed after sending the mail.

kind regards,
Chris

**Comment by xn--nding-jua** [comment] 2015-10-14 10:07
Regarding to the horde-API (https://dev.horde.org/api/master/lib/Imap_Client/class-Horde_Imap_Client_Mailbox.html) the call of "Horde_Imap_Client_Mailbox" should use a "false" at the end. Otherwise it assumes UTF-7? Can anyone with horde-knowledge check if a "false" will fix this problem safely?

```
$draftsMailBox = new \Horde_Imap_Client_Mailbox($draftsFolder->getFolderId(), true);
```
in https://github.com/owncloud/mail/blob/master/lib/account.php#L485 should be:
```
$draftsMailBox = new \Horde_Imap_Client_Mailbox($draftsFolder->getFolderId(), false);
```

**Comment by clementhk** [comment] 2015-10-15 00:14
@xn--nding-jua , `false -> utf7`.

**Comment by xn--nding-jua** [comment] 2015-10-15 05:42
Really?
![horde](https://cloud.githubusercontent.com/assets/9845353/10505680/4752043e-7310-11e5-9928-71e7a73f2344.png)

**Comment by clementhk** [comment] 2015-10-15 14:03
Oh @xn--nding-jua you could be right, I was looking at the wrong place. can you try it and let us know?

**Comment by clementhk** [comment] 2015-10-15 14:04
I think you are right, can you send a PR?

**Comment by xn--nding-jua** [comment] 2015-10-16 06:56
Yep, PR has been sent. I think this Issue can be closed.

**Comment by jancborchardt** [comment] 2015-11-05 15:14
Fixed by https://github.com/owncloud/mail/pull/1129 – thank you @xn--nding-jua, looking forward to future pull requests from you. :)

**Closed by jancborchardt** 2015-11-05 15:14 UTC
Labels: bug, needs info
