### ISSUE TITLE
Save addresses users have sent emails to

### ISSUE THREAD

**Issue by jakobsack** [owncloud/mail#999] opened 2015-08-31 08:59 UTC
The mail app should save addresses the users have sent mails to. In future, images should be loaded in emails from these addresses and the addresses should be suggested for auto completion.

- [ ] Create a model for these addresses
- [ ] Save the email addresse when sending emails

**Comment by jancborchardt** [comment] 2015-08-31 10:20
Duplicate of https://github.com/owncloud/mail/issues/879 ;) – let’s continue there. :)

Also: Save the email address of every mail in from/to/cc when receiving a mail.

**Closed by jancborchardt** 2015-08-31 10:20 UTC
Labels: 1 - to develop, enhancement
