### ISSUE TITLE
Bars representing mail accounts don't appear next to automatically downloaded emails

### ISSUE THREAD

**Issue by Bugsbane** [owncloud/mail#1210] opened 2016-01-07 05:13 UTC
When setting up multiple email accounts, and viewing the unified inbox, different coloured bars appear to the left of the various emails showing which account they come from.

When the page is loaded fresh, or if the "Check Messages..." button is clicked, all works as expected.

If I leave the tab open and new emails come in though, the new emails miss these coloured bars.

**Comment by ChristophWurst** [comment] 2016-01-07 09:00
Thanks for reporting. This is a duplicate of #1060

**Closed by ChristophWurst** 2016-01-07 09:00 UTC
