### ISSUE TITLE
TypeError: s is null

### ISSUE THREAD

**Issue by PoPoutdoor** [owncloud/mail#1088] opened 2015-09-16 02:36 UTC
Only after moving messages with other mail client, click on folder to recheck message.

[Nightly-20150916]

Console message -> js/vendor/domready/ready.min.js

**Comment by Gomez** [comment] 2015-09-21 19:56
Cant reproduce. Would you add more details (with step-by-step).
Thx

**Comment by PoPoutdoor** [comment] 2015-09-22 01:13
@Gomez 

Steps to reproduce:

1. empty a sub-folder's messages (by moving away/delete)
2. logout owncloud (to clear/expired cache)
3. login owncloud, use Mail
4. click on last emptied sub-folder
5. wait for console error while message list being updated

grep:

js/vendor/domready/ready.min.js:4:!function(e,t){typeof module!="undefined"?module.exports=t():typeof define=="function"&&typeof define.amd=="object"?define(t):this[e]=t()}("domready",function(){var e=[],t,n=document,r=n.documentElement.doScroll,i="DOMContentLoaded",s=(r?/^loaded|^c/:/^loaded|^i|^c/).test(n.readyState);return s||n.addEventListener(i,t=function(){n.removeEventListener(i,t),s=1;while(t=e.shift())t()}),function(t){s?setTimeout(t,0):e.push(t)}})

**Comment by PoPoutdoor** [comment] 2015-09-22 01:24
Just check another always emptied sub-folder, the error mesage:

TypeError: n is undefined

which points to the same code block.

FYI: I'm testing this with Gmail, the sub-folder are:

[Gmail]/junk, [Gmail/MailAppTest

**Comment by ChristophWurst** [comment] 2015-10-29 10:45
@PoPoutdoor I followed your steps and just got the 'No messages in this folder!' screen and no error at all.
Could you please try a fresh nightly and see if this error still occurs? Thanks.

**Comment by jancborchardt** [comment] 2015-11-05 15:02
Closing because assumed fixed. @PoPoutdoor if it still happens please reopen. :)

**Comment by PoPoutdoor** [comment] 2015-11-06 17:05
I still got this error! 

> OC 8.1.4
> php 5.6.14
> Firefox 38.4.0
> config: 'asset-pipeline.enabled' => true

I will try disable asset-pipeline for some days and see  if this is related.

**Comment by PoPoutdoor** [comment] 2015-11-15 15:44
Disable asset-pipeline doesn't change anything.

**Comment by ChristophWurst** [comment] 2015-11-17 18:51
Please enable debug mode so we can find out in which source js file the error is thrown. Also posting a screenshot of the stack trace would be very helpful. Thanks.

**Comment by Gomez** [comment] 2015-11-27 09:37
The Problem is here:
```
cache.js:71:7:
TypeError: message is null
```

**Comment by PoPoutdoor** [comment] 2015-11-27 11:04
Just about to post the same finding about cache.js... have to get used to work in debug console.

**Comment by PoPoutdoor** [comment] 2015-12-24 15:47
Please ignore the Jquery info reported here, that is not related to this issue.

**Comment by ChristophWurst** [comment] 2016-01-02 17:40
> Cant reproduce clearly, will debug.

@Gomez any idea where that error comes from?

**Comment by Gomez** [comment] 2016-01-08 16:29
Still needs debugging, but not a blocker > 0.3.1

**Comment by ChristophWurst** [comment] 2016-07-25 17:56
@Gomez @PoPoutdoor in case this is still an issue, please re-open. I could not reproduce this.

**Closed by ChristophWurst** 2016-07-25 17:56 UTC
Labels: 1 - to develop, bug, needs info
