### ISSUE TITLE
Use OpenPGP.js for email encryption

### ISSUE THREAD

**Issue by rakshazi** [owncloud/mail#916] opened 2015-07-31 09:27 UTC
Hello!
Mailenvelope is not very usable with OwnCloud, but you can implement [OpenPGP.js](http://openpgpjs.org/) for email encryption/decryption native in OwnCloud Mail app.

I hope that you will do this, because it's better than Mailenvelope as third-party browser plugin.

**Comment by DeepDiver1975** [comment] 2015-07-31 09:30
duplicate of #27

**Closed** 2015-07-31 09:30 UTC
