### ISSUE TITLE
Automatically import attached ics into calendar

### ISSUE THREAD

**Issue by arthurlutz** [owncloud/mail#723] opened 2015-05-25 19:41 UTC
It would be great if the mail application would detect if attachment is an icalendar file and automatically import it with the attached information into the calendar app.

**Comment by wurstchristoph** [comment] 2015-05-25 19:46
duplicate of #79

**Comment by jancborchardt** [comment] 2015-05-26 17:49
As @wurstchristoph said - let's continue in https://github.com/owncloud/mail/issues/79 :)

**Closed by jancborchardt** 2015-05-26 17:49 UTC
Labels: needs info
