### ISSUE TITLE
Default Mailserver / Docu

### ISSUE THREAD

**Issue by ltsavar** [owncloud/mail#1376] opened 2016-03-27 07:46 UTC
## ownCloud Mail

Hey,

is it posible to set a default mailserver via config.php? 
I did not find any documentation explaining that.

I use an imap backend for owncloud. So all owncloud users are emailadresses and the password is the same for both. It would be cool if there is an autologin to mail.

Regrads Ingo

**Comment by ChristophWurst** [comment] 2016-03-27 07:48
Hi @ltsavar,
this is a duplicate of https://github.com/owncloud/mail/issues/166

**Closed by ChristophWurst** 2016-03-27 07:48 UTC
