### ISSUE TITLE
Add signature to account

### ISSUE THREAD

**Issue by sonicmaster** [owncloud/mail#832] opened 2015-06-30 15:30 UTC
Add signature to account  , this is a must have.

**Comment by jancborchardt** [comment] 2015-06-30 17:50
@sonicmaster a quick search through existing issues for »signature« reveals that this is a duplicate of https://github.com/owncloud/mail/issues/654 :)

Same as for your other reported issue https://github.com/owncloud/mail/issues/825 – please check the existing issues first before opening another one. :)

**Closed by jancborchardt** 2015-06-30 17:50 UTC
Labels: needs info
