### ISSUE TITLE
Unifiedmailbox does not collect all mails

### ISSUE THREAD

**Issue by Gomez** [owncloud/mail#1566] opened 2016-07-18 17:57 UTC
My Unifiedmailbox does not show all mails of a second account. See this screenshot:

![mail_app](https://cloud.githubusercontent.com/assets/48724/16924836/7115e2ae-4d21-11e6-842d-be54321985df.png)

The domaindiscount24 mail is the first mail of the second accont, but there are newer mails. 

This error apear in the log:

Latest master, no caching.

```
{PHP} Undefined index: all-inboxes at htdocs/apps2/mail/lib/service/unifiedaccount.php#190
```
```
{PHP} Undefined offset: 34 at /htdocs/apps2/mail/lib/service/unifiedaccount.php#190
```

**Comment by ChristophWurst** [comment] 2016-07-21 07:18
duplicate of https://github.com/owncloud/mail/issues/1319

**Closed by ChristophWurst** 2016-07-21 07:18 UTC
Labels: 1 - to develop, bug
