### ISSUE TITLE
Native Encryption / Groupware App

### ISSUE THREAD

**Issue by aspdye** [owncloud/mail#776] opened 2015-06-16 08:40 UTC
OwnCloud supports encryption via the plugin Mailvelope. But would it not be great if you could integrate encryption directly in OwnCloud (OpenPGP), and would thus make it possible to retrieve e-mail (with encryption) from any browser.

In addition, the development of a OwnCloud Mail app would not be bad, with which one (even with encryption) to retrieve e-mails and can send. Maybe you could come togehter with the developers of calendar and contacts, so that there is in addition to the "Files" app also a kind of "groupware" app (Mail, Calendar, Contacts).

**Comment by DeepDiver1975** [comment] 2015-06-16 09:29
> OwnCloud supports encryption via the plugin Mailvelope. But would it not be great if you could integrate encryption directly in OwnCloud (OpenPGP), and would thus make it possible to retrieve e-mail (with encryption) from any browser.

duplicate of #27 



> Maybe you could come togehter with the developers of calendar and contacts, so that there is in addition to the "Files" app also a kind of "groupware" app (Mail, Calendar, Contacts).

I see no need in creating one groupware app - we shall integrate existing apps all together.

Thanks for your feedback!

**Closed by DeepDiver1975** 2015-06-16 09:29 UTC

**Comment by aspdye** [comment] 2015-06-16 09:31
@DeepDiver1975 Hi! Sorry. I dont mean a "OwnCloud App". I am meaning an Android, iOS App for Groupware. :)

**Comment by DeepDiver1975** [comment] 2015-06-16 09:47
> I dont mean a "OwnCloud App". I am meaning an Android, iOS App for Groupware. :)

Ah - I see - hmmm - but isn't it a combination of tool on mobile devices which gives you all required functions?

I mean there are calendars, addressbooks, mail and other messengers which all integrate.

**Comment by aspdye** [comment] 2015-06-16 09:57
I think just on Android works CalDAV, CardDAV and IMAP is not so perfectly together.Especially for beginners would be an app optimally.

**Comment by jancborchardt** [comment] 2015-06-16 10:15
Everything integrates via CalDAV, CardDAV and IMAP – we might be able to make the connection of those easier (through the ownCloud mobile app), but we should not write our own apps for Contacts, Calendar and Mail on mobile. ;D

**Comment by aspdye** [comment] 2015-06-16 11:29
@jancborchardt Yes. The OwnCloud-App is currently only showing files (i think). Other core-Apps should be supported as well :)
