### ISSUE TITLE
Icons of Folders are not shown - Problem with assets pipeline?

### ISSUE THREAD

**Issue by jakobsack** [owncloud/mail#1040] opened 2015-09-04 08:22 UTC
Hi, the icons next to the folders (like the inbox house) are not shown on my production system. On my development systems they are shown.
Both systems have a similar setup with mail app from git (feaa0e9e607de28eb2e92af644e0c98be6924d6c) and ownCloud 8.1.1.

Differences: The production system uses the assets pipeline and is in an subfolder, the development system does not use the pipeline and resides in the root folder.

Having a look at the web console it says "https://xxxx.yy/img/inbox.svg not found", the path to the file should be "https://xxxx.yy/owncloud/apps/mail/img/inbox.svg"

**Comment by tony5** [comment] 2015-09-04 09:47
I had this issue and the cause was the use of a theme.
some file in the css directory created this issue. 
maybe this is your problem as well?

**Comment by jakobsack** [comment] 2015-09-04 09:50
I'm not using any themes.

**Comment by jancborchardt** [comment] 2015-09-07 08:28
@ChristophWurst @Gomez @irgendwie any idea?

**Comment by irgendwie** [comment] 2015-09-07 09:17
@jakobsack My development ownCloud is reachable via `http://localhost/oc/...` and my production system is reachable via `http://cloud.exmaple.org/` therefore not reproducable for me! Both setups show the mail folder icons.

**Comment by jakobsack** [comment] 2015-09-07 12:25
@irgendwie Do you use the asset pipeline in one of the installations?

**Comment by tony5** [comment] 2015-09-07 13:18
I had this same exact problem when I had apps.css in my theme directory, although you said you don't use a theme maybe compare /core/css/apps.css on both systems?

**Comment by jancborchardt** [comment] 2015-11-05 15:18
@jakobsack @tony5 does it still happen? I could never reproduce.

**Comment by tony5** [comment] 2015-11-05 16:07
no it does not happen any more. the problem for me was (as stated above) that I had a problem with a custom theme that interfered with the mail app. I believe the problem was with apps.css in the theme directory.

once that was removed everything works as intended.

**Comment by jancborchardt** [comment] 2015-11-05 16:12
Ok, closing then. :) If it happens again let us know.

**Closed by jancborchardt** 2015-11-05 16:12 UTC
Labels: bug, needs info
