### ISSUE TITLE
Exchange IMAP denies connection

### ISSUE THREAD

**Issue by jeppebundsgaard** [owncloud/mail#687] opened 2015-05-18 15:39 UTC
I have connected to my private IMAP server, but when I want to connect to my company's Exchange IMAP-server, I get an error message saying: "Mail server denied authentication". The credentials work with my Thunderbird client. 
Please tell me which logfile output you need.

**Comment by jancborchardt** [comment] 2015-05-18 16:22
The details we need are described in the second paragraph at https://github.com/owncloud/mail#installation (issue template). Thanks! :)

**Comment by jeppebundsgaard** [comment] 2015-05-18 16:47
### Steps to reproduce
1. Press Add account and choose manual configuration
2. Insert Exchange IMAP server information and credentials
3.

### Expected behaviour
A new account should be created
### Actual behaviour
An error message: "Mail server denied authentication"

### Server configuration
**Operating system**: Ubuntu Linux 14.04

**Web server:** Apache

**Database:** Mysql

**PHP version:** 5.5.9-1ubuntu4.9

**ownCloud version:** (see ownCloud admin page) 8.03

**Updated from an older ownCloud or fresh install:** Update from 8.02 (I think, or 7-something)

**List of activated apps:** Mail, Calendar, Contacts, Activity

**The content of config/config.php:** 

```
A very large file... please tell me what you need from it.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 38
**Operating system:**
Kubuntu 15.04
### Logs
#### Web server error log
```
Nothing related
```

#### ownCloud log (data/owncloud.log)
```
Error 	mail 	Creating account failed: Mail server denied authentication. 	2015-05-18T16:38:02+00:00
Error 	PHP 	iconv(): Detected an illegal character in input string at /var/www/owncloud/apps/mail/lib/message.php#471 	2015-05-18T15:55:29+00:00
Error 	vobject 	Invalid VObject. Document ended prematurely. 	2015-05-18T15:53:47+00:00
Error	PHP	Invalid argument supplied for foreach() at /var/www/owncloud/apps/mail/lib/controller/folderscontroller.php#159	2015-05-18T15:51:34+00:00
Error	PHP	Invalid argument supplied for foreach() at /var/www/owncloud/apps/mail/lib/controller/folderscontroller.php#159	2015-05-18T15:50:04+00:00
Error	mail	Creating account failed: Mail server denied authentication.	2015-05-18T15:37:30+00:00
Error	mail	Creating account failed: Mail server denied authentication.	2015-05-18T15:36:45+00:00

#### Browser log
```
Nothing in the logs seems relevant

**Comment by jancborchardt** [comment] 2015-05-18 17:16
Maybe more is required for Exchange support? Is this a duplicate of https://github.com/owncloud/mail/issues/404 ?

**Comment by jeppebundsgaard** [comment] 2015-05-18 17:44
Thanks for responding!
No, it is not the same I ask for. My company has configured the exchange server to accept IMAP connections. It works fine on my Thunderbird client.

**Comment by DeepDiver1975** [comment] 2015-05-18 17:55
Please enable imap logging as explained in the readme - hopefully we gain some more information.

**Comment by jeppebundsgaard** [comment] 2015-05-18 18:21
Horde-log says:

````
------------------------------
>> Mon, 18 May 2015 18:18:43 +0000
>> Connection to: imap://SUBDOMAIN.DOMAIN.dk:993/
>> Server connection took 0.0992 seconds.
S: * OK The Microsoft Exchange IMAP4 service is ready.
C: 1 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN UIDPLUS ID CHILDREN IDLE NAMESPACE LITERAL+
S: 1 OK CAPABILITY completed.
>> Command 1 took 0.0337 seconds.
C: 2 [INITIAL CLIENT RESPONSE (username: DOMAIN\USER)]
S: +
C: YWRtZHB1bmV0XGplYnUAYWRtZHB1bmV0XGplYnUASHVuZDQ1Njc=
S: 2 NO AUTHENTICATE failed.
>> Command 2 took 0.1528 seconds.
````

I am SURE that my password is correct - checked several times.

**Comment by DeepDiver1975** [comment] 2015-05-18 18:52
Hmmm ..... maybe something we bring to attention upstream at the horde project. Hopefully they have an idea.

**Comment by Xenopathic** [comment] 2015-05-18 20:58
Looks like it could be related to this issue: https://confluence.atlassian.com/display/JIRAKB/Authenticate+Failed+Error+when+Connecting+to+Exchange

**Comment by ChristophWurst** [comment] 2016-03-17 16:37
@jeppebundsgaard please check if ownCloud Mail 0.4 fixes your issue as have updated horde libraries: https://apps.owncloud.com/content/show.php/Mail?content=169914
Please re-open if those errors still occur.

**Closed by ChristophWurst** 2016-03-17 16:37 UTC
Labels: bug, needs info

**Comment by ajcollett** [comment] 2016-10-17 07:48
Hello,

I saw the same issue connecting to my work office365 account. 

Then, after connecting an getting the "Authentication denied" error about 5 times, the same settings succeeded...

I am rather confused. Can anyone else confirm this is now working? Or did I fluke something?

Mail 0.6.0 

Any more info I can give?
