### ISSUE TITLE
Feature Request: Allow Admin to specify mail server details globally

### ISSUE THREAD

**Issue by squash** [owncloud/mail#1410] opened 2016-04-12 14:40 UTC
Using ownCloud with auth_external and using imap for authorization, so all ownCloud users are actually email users. Being able to pre-set the mail server information would be a huge help, particularly if we are able to include the user/pass used to log in to ownCloud.

**Comment by ChristophWurst** [comment] 2016-04-12 15:05
Duplicate of #166

**Closed by ChristophWurst** 2016-04-12 15:05 UTC
