### ISSUE TITLE
Add a way to select many mails instead of one, and delete or mark them as read/unread, favorite

### ISSUE THREAD

**Issue by ele0s** [owncloud/mail#1195] opened 2015-12-30 23:09 UTC
Hi,

Like the title said, we can't select many mails and operate on them

**Comment by phsc** [comment] 2015-12-30 23:21
Duplicate of #660 

The mail app is still in quite an early stage. Some features, that you know from almost all email clients, are still missing. Please have a look at all the issues tagged as "feature parity" https://github.com/owncloud/mail/labels/feature%20parity.

**Closed** 2015-12-30 23:30 UTC

**Comment by ChristophWurst** [comment] 2016-01-02 11:35
@ele0s please search for existing issues before opening new ones. Thanks.
