### ISSUE TITLE
require_config.js baseUrl path is wrong when app is installed in any location other than apps

### ISSUE THREAD

**Issue by aer0s** [owncloud/mail#1517] opened 2016-06-03 17:22 UTC
### Steps to reproduce
1. Create a secondary apps directory in config/config.php
2. Install mail plugin in this new or additional directory
3. Attempt to use application

### Expected behaviour
Require should load require should load additional js libraries from installed application directory.

### Actual behaviour
Require attempts to load additional js libraries from hard coded <FQDN>/apps/mail/<libname>.js
See line  17 in mail/js/require_config.js
`baseUrl: './../../../apps/mail/js',`

### ownCloud Mail

**ownCloud Mail version:** 0.5.1

**Mailserver or service:** Cyrus IMAP

**Transport security - IMAP:** STARTTLS 

**Transport security - SMTP:** STARTTLS

#### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
Apache2
**Database:**
Postgres 9.5
**PHP version:**
PHP 7.0.4
**ownCloud version:** (see ownCloud admin page)
9.0.2.2
**Updated from an older ownCloud or fresh install:**
Fresh
**List of activated apps:**
  - activity: 2.2.1
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.3.0.0
  - dav: 0.1.6
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - gallery: 14.5.0
  - mail: 0.5.1
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_external: 0.4
  - user_ldap: 0.8.0

**Comment by ChristophWurst** [comment] 2016-06-03 17:27
Exactly, duplicate of https://github.com/owncloud/mail/issues/1163 though. Wanna have a look and fix this? :-)

**Closed by ChristophWurst** 2016-06-03 17:27 UTC
