### ISSUE TITLE
images in message show up as attachments.

### ISSUE THREAD

**Issue by donniezazen** [owncloud/mail#652] opened 2015-05-11 12:10 UTC
As you can see in the pic below these are just social login icons that came with the html email and not actual images sent by the sender.

![snapshot61](https://cloud.githubusercontent.com/assets/841656/7564471/a2be2a14-f804-11e4-9532-3926b51f930c.png)

**Comment by DeepDiver1975** [comment] 2015-05-11 12:45
refs https://github.com/owncloud/mail/issues/138

**Comment by jancborchardt** [comment] 2015-05-11 14:18
Ah right – this is actually a duplicate of https://github.com/owncloud/mail/issues/138 – I’ll close this and we can continue there, ok @donniezazen? Bumped that original issue to 0.2

**Closed by jancborchardt** 2015-05-11 14:18 UTC
Labels: 1 - to develop, enhancement, priority
