### ISSUE TITLE
Can't access subfolders

### ISSUE THREAD

**Issue by LIyoai** [owncloud/mail#977] opened 2015-08-29 19:18 UTC
Subfolders are displayed on the left (folder.subfolder) , but I can not enter them.

**Comment by aspdye** [comment] 2015-08-29 21:20
Please follow the issue template so we get the info we need to be able to debug and fix the problem. Thanks!

**Comment by ChristophWurst** [comment] 2015-08-29 22:14
subfolders or subsubfolder? have a look at #618

**Comment by ChristophWurst** [comment] 2015-10-27 20:08
Closing this because we didn't get any information meanwhile and to me it seems like a duplicate of #618 or similar

**Closed by ChristophWurst** 2015-10-27 20:08 UTC
Labels: bug, needs info
