### ISSUE TITLE
Account creation screen is shown everytime the app is opened

### ISSUE THREAD

**Issue by Henni** [owncloud/mail#528] opened 2015-04-23 10:36 UTC
The mail app displays the "Connect your mail account" form every time I open the app or reload the page.
After inserting the same account details again the email account is listed multiple times.
(This means that the stored accounts are actually stored correctly in the database but not checked on startup)

**Comment by DeepDiver1975** [comment] 2015-04-23 12:45
hmmm - most probably related to the localstorage again ....

**Comment by ArndOtten** [comment] 2015-04-23 17:19
I had the same issue in firefox after a little complicated installation process. (Shared host, no ssh) 
Problem was fixed by using the JS console and run localStorage.clear()

**Comment by jancborchardt** [comment] 2015-04-23 17:35
@ArndOtten ok, thank you – then it definitely has something to do with the caching.

@ArndOtten @Henni you are also very welcome in our IRC channel #owncloud-mail! :)

**Comment by Henni** [comment] 2015-04-23 18:06
I had this issue on Chrome and localStorage.clear() solved it.
But it occurs again after deleting my account and readding it.

**Comment by zinks-** [comment] 2015-04-23 20:13
I think this is the same as #524

**Comment by jancborchardt** [comment] 2015-04-23 20:53
@ArndOtten @Henni can you confirm if this is the same as #524?

**Comment by Henni** [comment] 2015-04-24 08:12
Seems to be the same as #524

**Comment by jancborchardt** [comment] 2015-04-24 09:50
Closing as duplicate of https://github.com/owncloud/mail/issues/524 then, let’s continue there. :)

**Closed by jancborchardt** 2015-04-24 09:50 UTC
Labels: bug, needs info
