### ISSUE TITLE
Add an option for creating new contacts when sending/receiving emails to/from them.

### ISSUE THREAD

**Issue by rvega** [owncloud/mail#675] opened 2015-05-13 16:31 UTC
When sending or receiving an email from a person who is not in my contacts list (Contacts application), she should be added automatically to the contacts list, it'd probably be useful to add it to a group called "automatically added" or similar. 

Gmail does this by default and it's nice to simply start typing a name or address and have it auto-completed without having to manually create a contact.

**Comment by jancborchardt** [comment] 2015-05-13 17:15
This is a duplicate of https://github.com/owncloud/mail/issues/363 ;) let’s continue there.

**Closed by jancborchardt** 2015-05-13 17:15 UTC

**Comment by rvega** [comment] 2015-05-13 17:19
Ah, sorry, I swear I searched first :)

**Comment by jancborchardt** [comment] 2015-05-14 10:59
@rvega no worries, the search is often not perfect. :)
