### ISSUE TITLE
MAC email folder

### ISSUE THREAD

**Issue by piecam** [owncloud/mail#1141] opened 2015-10-23 00:36 UTC
Hi, 

first of all, nice app!!

However, I have another server with dovecot, postfix (email in a box). I can not modify/add/del folder with your app. Is there's anything I can do for now? Is it a limitiation?

I can use roundcube from (emailinabox) to manage folders.

thanks

**Comment by ChristophWurst** [comment] 2015-10-23 06:07
> I can not modify/add/del folder with your app. Is there's anything I can do for now? Is it a limitiation?

Not really, this app doesn't support that yet. There's one thing you can do: help us implement this feature ;-)

**Comment by piecam** [comment] 2015-10-23 10:50
HI Chris, 

Thanks for letting me know. Keep up good work!

peng

**Comment by jancborchardt** [comment] 2015-11-02 11:12
Hey @piecam, this is a duplicate of »Folder management and moving mails« – #411

Closing this hence, let’s keep the discussion there. :) And any contribution is welcome of course!

**Closed by jancborchardt** 2015-11-02 11:12 UTC
Labels: 1 - to develop, enhancement, feature parity
