### ISSUE TITLE
Unified inbox replying broken

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1128] opened 2015-10-15 05:27 UTC
Yet again unified inbox replies seem to be broken @ChristophWurst @irgendwie @Gomez @zinks- @PoPoutdoor  help :)

I did a fresh git pull from master and ran `make optimize-js` without errors. Replying from the single inbox works.

»Server error« as yellow notification, and this in the owncloud.log
```
{"reqId":"qPyY8I4jEfPKmy2mhj2Z","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\Db\\\\DoesNotExistException\",\"Message\":\"No matching entry found\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(346): OCP\\\\AppFramework\\\\Db\\\\Mapper->findOneQuery('SELECT * FROM `...', Array, NULL, NULL)\\n#1 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/db\\\/mailaccountmapper.php(47): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntity('SELECT * FROM `...', Array)\\n#2 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/service\\\/accountservice.php(51): OCA\\\\Mail\\\\Db\\\\MailAccountMapper->find('jan', 0)\\n#3 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/controller\\\/accountscontroller.php(357): OCA\\\\Mail\\\\Service\\\\AccountService->find('jan', 0)\\n#4 [internal function]: OCA\\\\Mail\\\\Controller\\\\AccountsController->draft(0, NULL, 'Message ...', '\\\"Name...', '', '', 0, '')\\n#5 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#6 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\AccountsController), 'draft')\\n#7 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\AccountsController), 'draft')\\n#8 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('AccountsControl...', 'draft', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#11 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/base.php(831): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#12 \\\/home\\\/jan\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/home\\\/jan\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php\",\"Line\":284}","level":3,"time":"2015-10-15T05:22:34+00:00"}
{"reqId":"+pYf8ro042z+QH+jBhfs","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\Db\\\\DoesNotExistException\",\"Message\":\"No matching entry found\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(346): OCP\\\\AppFramework\\\\Db\\\\Mapper->findOneQuery('SELECT * FROM `...', Array, NULL, NULL)\\n#1 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/db\\\/mailaccountmapper.php(47): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntity('SELECT * FROM `...', Array)\\n#2 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/service\\\/accountservice.php(51): OCA\\\\Mail\\\\Db\\\\MailAccountMapper->find('jan', 0)\\n#3 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/controller\\\/accountscontroller.php(262): OCA\\\\Mail\\\\Service\\\\AccountService->find('jan', 0)\\n#4 [internal function]: OCA\\\\Mail\\\\Controller\\\\AccountsController->send(0, '', NULL, 'Message ...', '\\\"Name...', '', '', 0, '', NULL)\\n#5 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#6 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\AccountsController), 'send')\\n#7 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\AccountsController), 'send')\\n#8 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('AccountsControl...', 'send', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#11 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/base.php(831): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#12 \\\/home\\\/jan\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/home\\\/jan\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php\",\"Line\":284}","level":3,"time":"2015-10-15T05:22:35+00:00"}
{"reqId":"fWPrZGUeRZT\/eLDm8bsS","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\Db\\\\DoesNotExistException\",\"Message\":\"No matching entry found\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(346): OCP\\\\AppFramework\\\\Db\\\\Mapper->findOneQuery('SELECT * FROM `...', Array, NULL, NULL)\\n#1 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/db\\\/mailaccountmapper.php(47): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntity('SELECT * FROM `...', Array)\\n#2 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/service\\\/accountservice.php(51): OCA\\\\Mail\\\\Db\\\\MailAccountMapper->find('jan', 0)\\n#3 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/controller\\\/accountscontroller.php(357): OCA\\\\Mail\\\\Service\\\\AccountService->find('jan', 0)\\n#4 [internal function]: OCA\\\\Mail\\\\Controller\\\\AccountsController->draft(0, NULL, 'Message ...', '\\\"Name...', '', '', 0, '')\\n#5 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#6 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\AccountsController), 'draft')\\n#7 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\AccountsController), 'draft')\\n#8 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('AccountsControl...', 'draft', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#11 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/base.php(831): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#12 \\\/home\\\/jan\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/home\\\/jan\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php\",\"Line\":284}","level":3,"time":"2015-10-15T05:22:38+00:00"}
```

Also got this in the JS console, not sure if it’s related
```
TypeError: s is null mail.min.js line 99
```

**Comment by ChristophWurst** [comment] 2015-10-15 06:00
> Also got this in the JS console, not sure if it’s related
> 
> TypeError: s is null mail.min.js line 99

Could be related. Please enable debug mode so source js files are used. If you can then reproduce the error, please also post the error message shown there. mail.min.js is compressed, hence I have no idea what the above error means.

**Comment by Gomez** [comment] 2015-10-15 08:23
Same JS error here:
https://github.com/owncloud/mail/issues/1088

**Comment by jancborchardt** [comment] 2015-11-05 15:17
Hm, I can not reliably reproduce that anymore.

**Comment by PoPoutdoor** [comment] 2015-11-06 08:48
Still got this with latest nightly:

> OC 8.1.1
> php 5.6.14

Seems related to php 5.6

**Comment by irgendwie** [comment] 2015-11-06 08:51
@PoPoutdoor Can't reproduce with ownCloud (master branch), mail (master branch) and php version 5.6.15

**Comment by PoPoutdoor** [comment] 2015-11-06 08:58
@irgendwie I will upgraded to latest 8.1.x later today, willreport back if this is fixed with latest 8.1 version.

**Comment by irgendwie** [comment] 2015-11-06 09:02
@PoPoutdoor because it isn't the first time someone is mentioning about 5.6 incompatibility, which OS do you use, where do you get PHP from?
Will check the issue for ubuntu 14.04 with php from Ondrej PPA later today.

**Comment by PoPoutdoor** [comment] 2015-11-06 13:21
@irgendwie I'm a long time Gentoo user, so almost every package was complied in from source. Since my other php application doesn't exploded, assumed my php package isn't broke or contains faulty code.

BTW, my OC upgrade stuck at maintenance mode (forever refresh), the test report will be post by tomorrow as I get that fixed and do the test.

**Comment by jancborchardt** [comment] 2015-11-12 08:58
I got this error again. Enabled debug mode now, and the owncloud log says:
```
{"reqId":"8PQqT3CeTVkg7DlC9TOy","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\Db\\\\DoesNotExistException\",\"Message\":\"No matching entry found\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(346): OCP\\\\AppFramework\\\\Db\\\\Mapper->findOneQuery('SELECT * FROM `...', Array, NULL, NULL)\\n#1 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/db\\\/mailaccountmapper.php(47): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntity('SELECT * FROM `...', Array)\\n#2 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/service\\\/accountservice.php(51): OCA\\\\Mail\\\\Db\\\\MailAccountMapper->find('jan', 0)\\n#3 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/controller\\\/accountscontroller.php(357): OCA\\\\Mail\\\\Service\\\\AccountService->find('jan', 0)\\n#4 [internal function]: OCA\\\\Mail\\\\Controller\\\\AccountsController->draft(0, NULL, 'Message bla...', '\\\"Name bla...', '', '', 0, '')\\n#5 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#6 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\AccountsController), 'draft')\\n#7 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\AccountsController), 'draft')\\n#8 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('AccountsControl...', 'draft', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#11 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/base.php(855): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#12 \\\/home\\\/jan\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/home\\\/jan\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php\",\"Line\":284}","level":3,"time":"2015-11-12T08:55:48+00:00"}
{"reqId":"5\/0pL5+GloTPuXpWqrAc","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\Db\\\\DoesNotExistException\",\"Message\":\"No matching entry found\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(346): OCP\\\\AppFramework\\\\Db\\\\Mapper->findOneQuery('SELECT * FROM `...', Array, NULL, NULL)\\n#1 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/db\\\/mailaccountmapper.php(47): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntity('SELECT * FROM `...', Array)\\n#2 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/service\\\/accountservice.php(51): OCA\\\\Mail\\\\Db\\\\MailAccountMapper->find('jan', 0)\\n#3 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/controller\\\/accountscontroller.php(262): OCA\\\\Mail\\\\Service\\\\AccountService->find('jan', 0)\\n#4 [internal function]: OCA\\\\Mail\\\\Controller\\\\AccountsController->send(0, '', NULL, 'Message bla...', '\\\"Name bla...', '', '', 0, '', NULL)\\n#5 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#6 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\AccountsController), 'send')\\n#7 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\AccountsController), 'send')\\n#8 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('AccountsControl...', 'send', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#11 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/base.php(855): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#12 \\\/home\\\/jan\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/home\\\/jan\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php\",\"Line\":284}","level":3,"time":"2015-11-12T08:55:48+00:00"}
{"reqId":"9SnYClerTSaVUfgVAW9A","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\Db\\\\DoesNotExistException\",\"Message\":\"No matching entry found\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(346): OCP\\\\AppFramework\\\\Db\\\\Mapper->findOneQuery('SELECT * FROM `...', Array, NULL, NULL)\\n#1 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/db\\\/mailaccountmapper.php(47): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntity('SELECT * FROM `...', Array)\\n#2 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/service\\\/accountservice.php(51): OCA\\\\Mail\\\\Db\\\\MailAccountMapper->find('jan', 0)\\n#3 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/controller\\\/accountscontroller.php(357): OCA\\\\Mail\\\\Service\\\\AccountService->find('jan', 0)\\n#4 [internal function]: OCA\\\\Mail\\\\Controller\\\\AccountsController->draft(0, NULL, 'Message bla...', '\\\"Name bla...', '', '', 0, '')\\n#5 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#6 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\AccountsController), 'draft')\\n#7 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\AccountsController), 'draft')\\n#8 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('AccountsControl...', 'draft', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#11 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/base.php(855): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#12 \\\/home\\\/jan\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/home\\\/jan\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php\",\"Line\":284}","level":3,"time":"2015-11-12T08:55:50+00:00"}
```

@ChristophWurst @irgendwie @Gomez :)

**Comment by jancborchardt** [comment] 2015-11-12 08:58
Let me know if I can debug anything else. There’s no error in the JS console anymore.

**Comment by PoPoutdoor** [comment] 2015-11-13 14:25
Test with Opera 12.16, opera dragonfly shows

![Uploading dragonfly.gif…]()

**Comment by Gomez** [comment] 2015-11-14 11:02
I played with it one hour. Cant get one of the errors. @ChristophWurst Does the php errors give you a clue? Something we can try?
Maybe we should add better logging / output for mailserver error messages in 0.4?

**Comment by Gomez** [comment] 2015-11-14 15:41
Got it now on my server:
```
 {index} Exception: {"Exception":"OCP\\AppFramework\\Db\\DoesNotExistException","Message":"No matching entry found","Code":0,"Trace":"#0 \/var\/www\/virtual\/cloud.portknox.net\/htdocs\/lib\/public\/appframework\/db\/mapper.php(346): OCP\\AppFramework\\Db\\Mapper->findOneQuery('SELECT * FROM `...', Array, NULL, NULL)\n#1 \/var\/www\/virtual\/cloud.portknox.net\/htdocs\/apps2\/mail\/lib\/db\/mailaccountmapper.php(47): OCP\\AppFramework\\Db\\Mapper->findEntity('SELECT * FROM `...', Array)\n#2 \/var\/www\/virtual\/cloud.portknox.net\/htdocs\/apps2\/mail\/lib\/service\/accountservice.php(51): OCA\\Mail\\Db\\MailAccountMapper->find('gomez', 0)\n#3 \/var\/www\/virtual\/cloud.portknox.net\/htdocs\/apps2\/mail\/lib\/controller\/accountscontroller.php(357): OCA\\Mail\\Service\\AccountService->find('gomez', 0)\n#4 [internal function]: OCA\\Mail\\Controller\\AccountsController->draft(0, NULL, '?Jo, da musst h...', '\"JXxxn Lxxxr...', '\"Email Verteile...', '', 0, '')\n#5 \/var\/www\/virtual\/cloud.portknox.net\/htdocs\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#6 \/var\/www\/virtual\/cloud.portknox.net\/htdocs\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Mail\\Controller\\AccountsController), 'draft')\n#7 \/var\/www\/virtual\/cloud.portknox.net\/htdocs\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Mail\\Controller\\AccountsController), 'draft')\n#8 \/var\/www\/virtual\/cloud.portknox.net\/htdocs\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('AccountsControl...', 'draft', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#9 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#10 \/var\/www\/virtual\/cloud.portknox.net\/htdocs\/lib\/private\/route\/router.php(274): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#11 \/var\/www\/virtual\/cloud.portknox.net\/htdocs\/lib\/base.php(874): OC\\Route\\Router->match('\/apps\/mail\/acco...')\n#12 \/var\/www\/virtual\/cloud.portknox.net\/htdocs\/index.php(48): OC::handleRequest()\n#13 {main}","File":"\/var\/www\/virtual\/cloud.portknox.net\/htdocs\/lib\/public\/appframework\/db\/mapper.php","Line":284}
```

**Comment by Gomez** [comment] 2015-11-14 17:42
@PoPoutdoor I found something, about the js error. Have you added a second 'apps_paths' to your config.php. And installed mail into it? If yes please move it to just 'apps' (where files is too). And retest please. At least the js Error should be gone.

Same ticket: #1088

**Comment by Gomez** [comment] 2015-11-14 17:45
@jancborchardt You can check this too. Paste your config.php please. Ever used the  'apps_paths' option in it?

**Comment by PoPoutdoor** [comment] 2015-11-15 15:39
@Gomez I haven't set second 'apps_paths' in config. However, I use link for testing those nightly builds:

> ln -s mail_20151111 mail

also, I may leave some nightly versions in apps directory... is this related to PHP PATHINFO?

**Comment by PoPoutdoor** [comment] 2015-11-15 16:01
Just restored to 'standard' - clear asset files, remove link, remove outdated nightly and rename latest nightly to 'mail', still got same error as #1088 while open account/folder, not Unified Inbox.

**Comment by Gomez** [comment] 2015-11-16 13:35
Thanks @PoPoutdoor. What you mean by 'standard'? Would you paste your config.php, please.

**Comment by PoPoutdoor** [comment] 2015-11-16 14:11
@Gomez 'standard' means most user will install apps from UI, i.e. don't do non-standard app installation with links like I do.

Config is minimum, no encryption with:

> 'overwrite.cli.url' => 'http://192.168.1.15/oc',
> 'asset-pipeline.enabled' => true,

**Comment by Gomez** [comment] 2015-11-21 19:36
I debugged the code a bit. Problem is here:
https://github.com/owncloud/mail/blob/master/js/communication.js#L134
As the Unified inbox is '-1' it fails to create the url:
"/index.php/apps/mail/accounts/%7BaccountId%7D/send"

@DeepDiver1975 & @ChristophWurst you solved this already somewhere (AFAIK)? How to get the correct accountId

**Comment by ChristophWurst** [comment] 2015-11-22 19:58
Even if ``accountId`` is set to ``-1`` the url should be created correctly. Could you debug that and find out what the actual value is?

**Comment by Gomez** [comment] 2015-11-26 10:35
Correct, the sendMessage function does not get all vars:
```
function sendMessage(accountId, message, options) 
```
accountId is null
message object has `body & to` set. But subject is missing (but there is one)
options object is missing nearly all values (messageId & folderid)

Because of this the send mail funtion in PHP fails (it finds the accounid over a lookup from the messageid).

I dont understand correctly how the sendMessage gets the vars? Can you give me some pointers.

**Comment by ChristophWurst** [comment] 2015-11-26 11:46
Found the error: The unified inbox hack for attaching ``accountId`` and ``folderId`` to messages is not implemented for bulk message loading.

**Comment by Gomez** [comment] 2015-11-26 11:50
Great! Looking forward to the code change!

**Closed** 2015-11-27 09:40 UTC
Labels: 1 - to develop, bug, in progress, priority
