### ISSUE TITLE
Attach file to answer mail

### ISSUE THREAD

**Issue by beccon4** [owncloud/mail#676] opened 2015-05-13 23:04 UTC
For the time being we can only answer a mail directly by typing int the form below. Unfortunately there is no way to attach a file there.

**Comment by jancborchardt** [comment] 2015-05-14 10:59
@beccon4 this is a duplicate of https://github.com/owncloud/mail/issues/460 – let’s continue there. :)

**Closed by jancborchardt** 2015-05-14 10:59 UTC
