### ISSUE TITLE
Broken php links in mail body

### ISSUE THREAD

**Issue by onny** [owncloud/mail#1489] opened 2016-05-10 20:14 UTC
### Steps to reproduce
1. Send yourself a mail with following link in the text field: https://wiki.archlinux.org/index.php?title=Gitlab&diff=next&oldid=434207
2. Open recieved mail
3. Link is now broken and looks like this:  wiki.archlinux.org/index.php&diff=next&oldid=434207

### Expected behaviour
Full and functional link in mail body

### Actual behaviour
Link is broken and incomplete

### ownCloud Mail

**ownCloud Mail version:** 0.4.4

**Mailserver or service:** Own IMAP server

**Transport security - IMAP:** STARTTLS

**Transport security - SMTP:** STARTTLS

**Number of accounts:** 1

**ownCloud Mail version build date:** (only if you are using a Nightly Build)

[...]

Best regards,
Jonas

**Comment by ChristophWurst** [comment] 2016-05-10 20:18
Hi @onny,
this is a duplicate of https://github.com/owncloud/mail/issues/930, so I'm closing this issue.
Thanks

**Closed by ChristophWurst** 2016-05-10 20:18 UTC
