### ISSUE TITLE
Feature request: Compact view

### ISSUE THREAD

**Issue by mcladyz** [owncloud/mail#946] opened 2015-08-17 06:54 UTC
Would be great if the mail app had a optional 'compact view', where only the mail account names are shown (Instead of all the folders). The number of new unread messages could be shown next to the account name.

This is useful if you have more than a couple mail accounts and wanna see the overall status.

**Comment by ChristophWurst** [comment] 2015-08-17 07:42
duplicate of #677

**Closed by ChristophWurst** 2015-08-17 07:42 UTC
