### ISSUE TITLE
Undefined index: REQUEST_URI

### ISSUE THREAD

**Issue by enoch85** [owncloud/mail#657] opened 2015-05-11 20:05 UTC
### Steps to reproduce

1. "Login" to your mail (Open your mail in ownCloud)

### Actual behaviour

It works, but I get this message in log.

```
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/calendar/appinfo/app.php#41	2015-05-11T20:00:01+00:00
```

I know it says calendar, but it happens when I open the mail app.

### Expected behaviour

No errors

### Server and Version

8.0.3
PHP 5.5
Mail 0.1

**Comment by DeepDiver1975** [comment] 2015-05-11 20:15
Cries for fixing calendar and contacts.

**Comment by enoch85** [comment] 2015-05-11 20:16
@DeepDiver1975 Please CC the correct persons.

**Comment by jancborchardt** [comment] 2015-05-11 20:26
cc @georgehrke @raghunayyar @libasys for Calendar

**Comment by georgehrke** [comment] 2015-05-11 20:55
Already fixed, just needs to be backported and released

Please excuse my brevity and typos.

**Comment by jancborchardt** [comment] 2015-05-12 01:03
@georgehrke so did you backport it?

**Comment by DeepDiver1975** [comment] 2015-05-12 07:14
> Already fixed, just needs to be backported and released

gogogo

**Comment by georgehrke** [comment] 2015-05-12 07:37
@jan It was closed a few days back already, haven't found enough  time to carefully test on stable8 yet. So no, it wasn't backported yet.

@thomas: there is an issue in the calendar repo, you can close this one.

Please excuse my brevity and typos.

**Comment by georgehrke** [comment] 2015-05-12 07:39
@jan and you are very welcome to actually help test PRs labeled backport_necessary on stable8 ;) 

Please excuse my brevity and typos.

**Comment by DeepDiver1975** [comment] 2015-05-12 07:40
> @thomas: there is an issue in the calendar repo, you can close this one.

please link the issue - thx

**Comment by enoch85** [comment] 2015-05-13 09:37
@jancborchardt I think this should go in under 0.2 as it spams the log. Question is, as this issue is related to the calendar, will *that* release be released before 0.2 or after? cc @georgehrke

**Comment by georgehrke** [comment] 2015-05-13 09:41
This has absolutely nothing to do with mail. It caused by the cron job.

Please excuse my brevity and typos.

**Comment by enoch85** [comment] 2015-05-13 09:46
@georgehrke Ok, misunderstood. Anyway: 

> @thomas: there is an issue in the calendar repo, you can close this one.

> please link the issue - thx

**Comment by georgehrke** [comment] 2015-05-15 08:08
dup of https://github.com/owncloud/calendar/issues/714

**Closed by georgehrke** 2015-05-15 08:08 UTC
Labels: 1 - to develop, bug, needs info
