### ISSUE TITLE
README.md - "Developer setup info" is not clear

### ISSUE THREAD

**Issue by PoPoutdoor** [owncloud/mail#1061] opened 2015-09-08 18:01 UTC
I think these will encourage admin level user to try out what's coming next in Mail app.

1. please provide non-distribution specified instructions (with whatever distribution specified instructions you guys using).

2. provide external lib download links (for distributions without said lib package)

3. instructions should be working

**Comment by ChristophWurst** [comment] 2015-09-08 19:02
> please provide non-distribution specified instructions (with whatever distribution specified instructions you guys using).

"Just clone this repo into your apps directory (ownCloud core installation needed). Additionally you need Composer to install PHP dependencies and npm to get the Javascript dependencies" is non-distribution specific ;-)
The only 'distribution-specific' instruction/command is ``sudo install node nodejs-legacy``. I'm ok with removing this line, we have the ``install_ubuntu.sh`` file for ubuntu/debian users anyway.

> provide external lib download links (for distributions without said lib package)

Can't be done easily. We rely on the folder structure of npm/bower packages, so we would need to have  instructions for all of the dependencies listed in https://github.com/owncloud/mail/blob/master/package.json and https://github.com/owncloud/mail/blob/master/bower.json . This doesn't make any sense to me. Which distribution doesn't provide ``npm``? It's easier to get install ``npm`` on your distro than downloading and configuring ~10 js libraries ;-)


> instructions should be working

Is there anything that doesn't?


Anyways, I think we're back to the idea of nightly builds as shortly discussed at the recent owncloud conf…

@jancborchardt @Gomez @enoch85 how about providing nightlies? As soon as #981 has been fixed, that should be easy to do. We just need some server to distribute it automatically.

**Comment by enoch85** [comment] 2015-09-08 19:40
@ChristophWurst Yes, I think nighties are the easiest way to go here, to stop confusion. Isn't GitHub providing the server needed for this task? Feel free to use my server otherwise. :)

**Comment by ChristophWurst** [comment] 2015-09-08 19:57
> @ChristophWurst Yes, I think nighties are the easiest way to go here, to stop confusion. Isn't GitHub providing the server needed for this task?

Unfortunately no, it's only possible to provide zip files for releases. (We don't want to have an release every day ;-) )



> Feel free to use my server otherwise. :)

Awesome! The easiest way to do this would probably be a simple BASH script that pulls the current master from GitHub and creates the package.

**Comment by enoch85** [comment] 2015-09-08 21:57
@ChristophWurst As I´m totally new to git, do you think you could write that BASH script? Later I can test it and later publish a domian specially for the cause. Or do you maybe have a better idea?

Where will the nighties be linked? Here on GitHub?

**Comment by enoch85** [comment] 2015-09-08 22:00
...or maybe I can use one of the existing ownCloud servers that I possess and just make a folder with all the nighties in it. Then we would only need to link that shared link, ownCloud style. ;)

**Comment by enoch85** [comment] 2015-09-08 23:09
@ChristophWurst No need for a script, I think I got it. Will upload the first nighty soon. :)

**Comment by Gomez** [comment] 2015-09-09 07:21
Nice! I like the ownCloud nightly style. You need to add the composer and npm stuff:

```
php composer.phar install
php composer. steps
```
And we first need to get https://github.com/owncloud/mail/pull/1055 in. Its needed for the js parts

**Comment by enoch85** [comment] 2015-09-09 10:02
@Gomez I "install" this on a system that already has the mail app installed. Not sure how I would install node-js and that stuff in just a separate folder? How do you do when you release? Can GitHub make such packages?

**Comment by Gomez** [comment] 2015-09-09 10:24
No Github cant do this. Normally Jenkins or a cron can do this. 

Right now node-js needs to be installed globally into the linux system. Than extend the bash script with our Makefile from #1055. 

Would be good get #1055 (and https://github.com/owncloud/mail/pull/1005) finished. Than we can come back to the nighlies.

**Comment by enoch85** [comment] 2015-09-09 10:58
@ChristophWurst @Gomez Please fork my script https://gist.github.com/enoch85/c710773f0bccd74ace30 or make a new one so that I can make a cronjob and start building nightlies :)

**Comment by ChristophWurst** [comment] 2015-09-09 11:22
> @ChristophWurst @Gomez Please fork my script https://gist.github.com/enoch85/c710773f0bccd74ace30 or make a new one so that I can make a cronjob and start building nightlies :)

Done: https://gist.github.com/ChristophWurst/24cf9bbde417a113c2bb ;-)

Things left to do:
* [ ] use Makefile once #1055 is merged

**Comment by enoch85** [comment] 2015-09-09 11:50
@ChristophWurst Ok, I added the missing lines and installed node-js to my system. Test if it works as it should: https://en0ch.se/index.php/s/3v5J3XXeQCCp73p

**Comment by PoPoutdoor** [comment] 2015-09-09 15:40
:+1: for  the nightly build idea. Does nightly build self-contain or still need user to install 3rdparty libs?

> Which distribution doesn't provide npm? It's easier to get install npm on your distro than downloading and configuring ~10 js libraries ;-)

@ChristophWurst I'm a Gentoo user and no npm package ATM. Anyway, let's focus on nightly build.

**Comment by ChristophWurst** [comment] 2015-09-09 15:48
> :+1: for the nightly build idea. Does nightly build self-contain or still need user to install 3rdparty libs?

It should be self-contained, like if you downloaded the app from the app store: unzip, enable, done.

**Comment by enoch85** [comment] 2015-09-09 17:34
@ChristophWurst I see this error running as root:

```
> mail@0.3.0 bower_deps /mail
> ./node_modules/.bin/bower install

bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your sys                                tem should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
Script npm run-script bower_deps handling the post-install-cmd event returned with an error



  [RuntimeException]
  Error Output: bower ESUDO         Cannot be run with sudo
  Additional error details:
  Since bower is a user command, there is no need to execute it with superuser permissions.
  If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how you
  r system should work and make any necessary repairs.
  http://www.joyent.com/blog/installing-node-and-npm
  https://gist.github.com/isaacs/579814
  You can however run a command with sudo using --allow-root option
  npm ERR! weird error 1
  npm WARN This failure might be due to the use of legacy binary "node"
  npm WARN For further explanations, please read
  /usr/share/doc/nodejs/README.Debian

  npm ERR! not ok code 0
```

What should I do?

**Comment by ChristophWurst** [comment] 2015-09-09 18:32
> What should I do?

I guess you ran the script as root? Create the packages as an unprivileged user and then move it (as root if needed).

**Comment by enoch85** [comment] 2015-09-09 18:45
@ChristophWurst I have a another soulution. 

In package.json I changed this:
```
"bower_deps": "./node_modules/.bin/bower install"
```

To this:
```
"bower_deps": "./node_modules/.bin/bower install --allow-root"
``` 

And it worked. Could we change that in our code? Would make my life so much easier. :)

**Comment by ChristophWurst** [comment] 2015-09-09 18:51
@enoch85 you can change that, but at  your own risk… 

Generally speaking, don't run everything as root. It's simply not necessary here

**Comment by enoch85** [comment] 2015-09-09 19:28
@ChristophWurst 

```
# Install PHP/JS Dependencies
cd /mail
curl -sS https://getcomposer.org/installer | php
sed -i 's/"bower_deps": "./node_modules/.bin/bower install"/"bower_deps": "./node_modules/.bin/bower install --allow-root"/g' /mail/package.json
php composer.phar install
cd ..
```

This is what I menat with `sed -i`

**Comment by enoch85** [comment] 2015-09-09 22:33
Nightlies now work with bower included.

**Comment by ChristophWurst** [comment] 2015-09-10 07:09
> Nightlies now work with bower included.

Awesome! Works :+1:

**Comment by enoch85** [comment] 2015-09-10 11:17
@PoPoutdoor Please review https://github.com/owncloud/mail/pull/1066

**Comment by PoPoutdoor** [comment] 2015-09-10 12:41
@enoch85 The nightly file extracts without error, also shown in App list as 0.3 alpha.

I got 500 when open:

> Could not find resource file "/oc/apps/mail/js/mail.min.js"

**Comment by enoch85** [comment] 2015-09-10 12:45
@ChristophWurst Any idea?

**Comment by enoch85** [comment] 2015-09-10 12:46
@PoPoutdoor Did you download the latest version? I just updated it. Please try again.

**Comment by ChristophWurst** [comment] 2015-09-10 13:37
@enoch85 this error is thrown if the javascript optimizer is not run before packaging.

Which script do you use to create the nightly? Our Makefile?

We should probably wait for #1065

**Comment by PoPoutdoor** [comment] 2015-09-10 14:46
@enoch85 Just extracts a fresh download, *mail.min.js* still missing.

**Comment by enoch85** [comment] 2015-09-10 15:37
@ChristophWurst 

```
# Clone Mail master
git clone https://github.com/owncloud/mail.git $NIGHTLY_TMP

# Install PHP/JS Dependencies
cd /mail
curl -sS https://getcomposer.org/installer | php
sed -i "s|${JSON1}|${JSON2}|g" /mail/package.json
php composer.phar install
```

That should be enough, right?

**Comment by enoch85** [comment] 2015-09-10 16:30
@ChristophWurst package.json does a `npm install` as well when I run `php composer.phar install`. If I would use the Makefile I would need to run `php composer.phar install` and then `make` because without `php composer.phar install` I don´t get the `horde` install. Could you guys maybe include the `horde`install in the `Makefile` as well? Or is that a bad idea?

**Comment by PoPoutdoor** [comment] 2015-09-12 10:16
@enoch85 The 20150912 build works, thanks!

**Comment by enoch85** [comment] 2015-09-12 14:59
@PoPoutdoor Glad to hear!

**Closed** 2015-09-12 21:50 UTC
Labels: 1 - to develop, discussion, enhancement
