### ISSUE TITLE
Sub-sub folders not handled correctly

### ISSUE THREAD

**Issue by Xenopathic** [owncloud/mail#618] opened 2015-05-05 23:54 UTC
I have a subfolder of a subfolder, and it appears as 'SubFolder.SubSubFolder' instead of as a dropdown. Also it’s not loaded. Other email clients correctly deduce the sub-subfolder structure.

**Comment by jancborchardt** [comment] 2015-05-06 00:29
We decided to flatten the hierarchy like that. The folder should be accessible though.

**Comment by Xenopathic** [comment] 2015-05-06 07:51
@jancborchardt Doesn't that defeat the purpose of sub-subfolders, which is to restrict the number of folders being shown? I see why it was done, but I think there should be a dropdown (even if there is no indentation inside the dropdown)

**Comment by jancborchardt** [comment] 2015-05-06 08:37
Yeah, something for 0.2 then probably. ;)

The important thing is: You are able to open sub-subfolders, right?

**Comment by Xenopathic** [comment] 2015-05-06 08:53
As far as I can tell, no. The spinners just sit there endlessly. I can see the request to get a message list is sent, and an (empty) response is received, but the spinners never end. This happens for ordinary subfolders too.

**Comment by jancborchardt** [comment] 2015-05-06 08:56
Ah right, that’s https://github.com/owncloud/mail/issues/611 then – can you test if https://github.com/owncloud/mail/pull/616 fixes that for you?

(I’m changing this "add dropdown for sub-subfolders" as enhancement.)

**Comment by jancborchardt** [comment] 2015-06-17 15:08
So can someone work on this for 0.2? Kinda important that the sub-subfolder content is loaded. We don’t necessarily need to style it right, but it should work.

@irgendwie @wurstchristoph @zinks- @Xenopathic? :)

**Comment by 1337sup3rh4x0r** [comment] 2015-06-29 07:41
For me, the content of sub-sub folders does not load either. Am I correctly assuming that #616 did not fix #611? The code on my machine looks like #616 is already merged.

**Comment by jancborchardt** [comment] 2015-06-29 10:14
@1337sup3rh4x0r well, #616 did fix #611 which was about subfolders (1 level). But this issue, which is about sub-subfolders (2nd level and deeper) is still open. So no, it’s not fully fixed yet.

**Comment by DeepDiver1975** [comment] 2015-06-29 11:40
out of scope for me with respect to 0.2 - objections?

**Comment by 1337sup3rh4x0r** [comment] 2015-06-29 12:49
bummer. Basically all my mails are stored in Sub-sub folders. I'll be watching this space till 0.3 then.

**Comment by jancborchardt** [comment] 2015-06-29 12:54
@1337sup3rh4x0r sorry about that! :) If you are what your name promises though, you could submit a pull request to fix the issue? ;D

**Comment by 1337sup3rh4x0r** [comment] 2015-06-29 14:40
:D yeah, let me just read a JavaScript manual real quick

**Comment by hanslammerts** [comment] 2016-01-31 15:19
OK, So what does this mean ? We have to wait until 0.4 ?

**Comment by ChristophWurst** [comment] 2016-01-31 15:38
> OK, So what does this mean ? We have to wait until 0.4 ?

Yes and no. It's planned for 0.4 but there's no guarantee that someone will implement it. However, @hanslammerts you don't have to wait, you can also simply fix that by yourself now ;-) Do you have JavaScript experience?

**Comment by hanslammerts** [comment] 2016-01-31 15:45
I'm afraid I don't have enough experience with js to be able to help you out, if you're asking to participate in the project. Sorry !

**Comment by ErikPel** [comment] 2016-01-31 16:19
I can take a look (No promises though). How can I reproduce this issue? I'm not quite getting which folders we are talking about here. @ChristophWurst @hanslammerts

**Comment by ChristophWurst** [comment] 2016-01-31 16:21
> I can take a look (No promises though). How can I reproduce this issue? I'm not quite getting which folders we are talking about here. @ChristophWurst @hanslammerts

Awesome! Let me know if you need any help :-)

Fire up another mail client and create a folder hierarchy of at least 2 levels. Subfodlers should work, but Sub-sub folder don't.

**Closed** 2016-02-02 11:25 UTC
Labels: 3 - to review, bug, feature parity, in progress, priority
