### ISSUE TITLE
Problem Spinning icon after adding new imap account (exchange 2013)

### ISSUE THREAD

**Issue by apg1980** [owncloud/mail#721] opened 2015-05-25 08:00 UTC
Hi,
i've upgradet to the latest mail version.
i disabled first the app in owncloud, deleted database tables and installed all dependencies.
after adding my mail account the same way before the horde.log is showing all mail folders whitin my account but the mails didnt appear.

last lines from horde.log:
S: * STATUS Junk-E-Mail (MESSAGES 0 RECENT 0 UIDNEXT 18 UIDVALIDITY 213 UNSEEN 0)
S: 132 OK STATUS completed.
>> Command 132 took 1.4436 seconds.
S: 133 NO Server Unavailable. 15
>> Command 133 took 1.4437 seconds.
S: * STATUS Synchronisierungsprobleme/Konflikte (MESSAGES 0 RECENT 0 UIDNEXT 1 UIDVALIDITY 324 UNSEEN 0)
S: 134 OK STATUS completed.
>> Command 134 took 1.4444 seconds.
S: 135 NO Server Unavailable. 15
>> Command 135 took 1.4445 seconds.
S: * BYE Connection closed. 14

the spinning icon still appear.

owncloud log says the following:
Exception: {"Message":"IMAP Server 
"IMAP Server closed the connection.","Code":4,"Trace":"#0 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php(4209): Horde_Imap_Client_Socket->_getLine(Object(Horde_Imap_Client_Interaction_Pipeline))\n#1 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php(4137): Horde_Imap_Client_Socket->_sendCmdChunk(Object(Horde_Imap_Client_Interaction_Pipeline), Array)\n#2 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php(1656): Horde_Imap_Client_Socket->_sendCmd(Object(Horde_Imap_Client_Interaction_Pipeline))\n#3 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Base.php(1724): Horde_Imap_Client_Socket->_status(Array, 63)\n#4 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/apps\/mail\/lib\/account.php(219): Horde_Imap_Client_Base->status(Array)\n#5 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/apps\/mail\/lib\/controller\/folderscontroller.php(62): OCA\\Mail\\Account->getListArray()\n#6 [internal function]: OCA\\Mail\\Controller\\FoldersController->index()\n#7 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/http\/dispatcher.php(158): call_user_func_array(Array, Array)\n#8 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/http\/dispatcher.php(86): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Mail\\Controller\\FoldersController), 'index')\n#9 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/app.php(97): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Mail\\Controller\\FoldersController), 'index')\n#10 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/routing\/routeactionhandler.php(44): OC\\AppFramework\\App::main('FoldersControll...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#11 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#12 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/route\/router.php(250): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#13 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/base.php(782): OC\\Route\\Router->match('\/apps\/mail\/acco...')\n#14 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/index.php(36): OC::handleRequest()\n#15 {main}","File":"\/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php","Line":4511} 

i cannot figure out why owncloud is saying ""IMAP Server 
"IMAP Server closed the connection"

Additional information:
ubuntu 14.4
owncloud 8.3
mysql 5.5.39
php 5.4.32

Owncloud Apps: user_ldap, activity, deleted files, documents, external storage support, files clipboard, first run wizard, gallery+, impersonate, mail, news, mozilla sync, pdf viewer, ownnote, share files

**Comment by apg1980** [comment] 2015-05-25 16:46
Additional information:
ubuntu 14.4
owncloud 8.3
mysql 5.5.39
php 5.4.32

Owncloud Apps: user_ldap, activity, deleted files, documents, external storage support, files clipboard, first run wizard, gallery+, impersonate, mail, news, mozilla sync, pdf viewer, ownnote, share files

**Comment by wurstchristoph** [comment] 2015-05-25 22:02
Hi @apg1980,
could you please post more of your horde log? It seems like you included only IMAP responses (lines starting with ``S:``. To debug this, it would help to know which commands where sent to the IMAP server (lines starting with ``C: ``). Thanks!

**Comment by apg1980** [comment] 2015-06-03 04:23
------------------------------
>> Wed, 03 Jun 2015 04:17:02 +0000
>> Connection to: imap://10.10.20.24/
>> Server connection took 0.0095 seconds.
S: * OK The Microsoft Exchange IMAP4 service is ready.
C: 1 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN STARTTLS UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
S: 1 OK CAPABILITY completed.
>> Command 1 took 0.0062 seconds.
C: 2 [INITIAL CLIENT RESPONSE (username: p.grunenberg)]
S: +
C: cC5ncnVuZW5iZXJnAHAuZ3J1bmVuYmVyZwBQYXRhdG9yNDAxNTU3OTk=
S: 2 OK AUTHENTICATE completed.
>> Command 2 took 0.2119 seconds.
C: 3 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
S: 3 OK CAPABILITY completed.
>> Command 3 took 0.0022 seconds.
C: 4 LIST "" *

**Comment by jancborchardt** [comment] 2015-06-09 19:38
@wurstchristoph does that help? Or does anyone else have an idea @zinks- @clementhk @DeepDiver1975?

**Comment by wurstchristoph** [comment] 2015-06-09 20:37
@jancborchardt unfortunately no, this doesn't help me.

@apg1980 could you please post the full horde output? (From the beginning of the IMAP request, like the ``>> Wed, 03 Jun 2015 04:17:02 +0000`` line above, to the very last command sent to or received from the IMAP server like ``S: * BYE Connection closed.``) :-)

**Comment by apg1980** [comment] 2015-06-10 04:57
there are a lot of personal information within the log. is this necessary?

>> Wed, 10 Jun 2015 04:41:50 +0000
>> Connection to: imap://10.10.20.24/
>> Server connection took 0.001 seconds.
S: * OK The Microsoft Exchange IMAP4 service is ready.
C: 1 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN STARTTLS UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
S: 1 OK CAPABILITY completed.
>> Command 1 took 0.5928 seconds.
C: 2 [INITIAL CLIENT RESPONSE (username: p.grunenberg)]
S: +
C: cC5ncnVuZW5iZXJnAHAuZ3J1bmVuYmVyZwBQYXRhdG9yNDAxNTU3OTk=
>> Slow Command: 14.977 seconds
S: 2 OK AUTHENTICATE completed.
>> Command 2 took 15.7683 seconds.
C: 3 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
S: 3 OK CAPABILITY completed.
>> Command 3 took 0.1431 seconds.
>> CACHE: Using the OCA\Mail\Cache\Cache storage driver.
C: 4 LIST "" *

###############lot of folders with real names ##############

S: 4 OK LIST completed.
>> Command 4 took 0.338 seconds.
C: 5 STATUS INBOX (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)

###############lot of folders with real names ##############

S: 5 OK STATUS completed.
>> Command 5 took 0.8387 seconds.

###############lot of folders with real names ##############

S: 22 NO Server Unavailable. 15

###############lot of folders with real names ##############

S: * STATUS Journal (MESSAGES 0 RECENT 0 UIDNEXT 1 UIDVALIDITY 211 UNSEEN 0)
S: 106 OK STATUS completed.
>> Command 106 took 2.744 seconds.
S: * STATUS Junk-E-Mail (MESSAGES 0 RECENT 0 UIDNEXT 21 UIDVALIDITY 213 UNSEEN 0)
S: 107 OK STATUS completed.
>> Command 107 took 2.7445 seconds.
S: 108 NO Server Unavailable. 15
>> Command 108 took 2.7446 seconds.
S: * STATUS Synchronisierungsprobleme/Konflikte (MESSAGES 0 RECENT 0 UIDNEXT 1 UIDVALIDITY 324 UNSEEN 0)
S: 109 OK STATUS completed.
>> Command 109 took 2.7454 seconds.
S: 110 NO Server Unavailable. 15
>> Command 110 took 2.7455 seconds.
S: * BYE Connection closed. 14

**Comment by DeepDiver1975** [comment] 2015-06-10 07:12
> S: 108 NO Server Unavailable. 15
Command 108 took 2.7446 seconds.
S: * STATUS Synchronisierungsprobleme/Konflikte (MESSAGES 0 RECENT 0 UIDNEXT 1 UIDVALIDITY 324 UNSEEN 0)



Looks like a server issue - not much we can do ...


Maybe we shall get in touch with the horde project to see if this is an issue in the imap client.

**Comment by apg1980** [comment] 2015-06-10 17:15
No Server unavailable = server is available, because server is no unavailable....??????confusing

**Comment by DeepDiver1975** [comment] 2015-06-17 15:59
> Maybe we shall get in touch with the horde project to see if this is an issue in the imap client.

Can any body please get in touch with the horde project to see if there is a known issue within the horde imap client? THX

**Comment by jancborchardt** [comment] 2015-07-15 15:36
Closing as duplicate of https://github.com/owncloud/mail/issues/687

**Closed by jancborchardt** 2015-07-15 15:37 UTC
Labels: bug, needs info
