### ISSUE TITLE
feature request: button to mark an email unread again

### ISSUE THREAD

**Issue by daniel309** [owncloud/mail#1104] opened 2015-09-18 15:01 UTC
I use read/unread marks as my todo list for mail. The only thing that keeps me from using the owncloud mail app regularly is a button (or sth. else) to mark an email that I already read as unread again. 

Would be great if you could find some time to work on that

Daniel

**Comment by ChristophWurst** [comment] 2015-09-18 15:15
Thanks for reporting. That's a duplicate of #672.

Are you familiar with javascript? It shouldn't be too hard to add that feature ;-)

As an alternative, you could use the star/unstar functionality we already support to manage your todos in the meantime!

**Closed** 2015-09-18 15:36 UTC
