### ISSUE TITLE
Signature could not be checked

### ISSUE THREAD

**Issue by joe-liberty** [owncloud/mail#1386] opened 2016-03-30 23:31 UTC
### Steps to reproduce
1. Fails to enable mail app
2.
3.

### Expected behaviour
It should enable app

### Actual behaviour
Signature could not get checked. Please contact the app developer and check your admin screen.

**OwnCloud Mail version:** 0.4.1

**Mailserver or service:** None

**Transport security - IMAP:**None

**Transport security - SMTP:** None

**Number of accounts:**

**ownCloud Mail version build date:** (only if you are using a Nightly Build)

### Server configuration
**Operating system**:Ubuntu 14.04 Server

**Web server:**Apache2

**Database:**Mysql

**PHP version:**5.5.9

**ownCloud version:** 9.0

**Updated from older version:**

**List of activated apps:** activity: 2.2.1
  - calendar: true
  - comments: 0.2
  - contacts: true
  - dav: 0.1.5
  - documents: 0.12.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:** 

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)

<?php
$CONFIG = array (
  'instanceid' => 'oc96dnu99pom',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => '********',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://**********/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.0.0.19',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'user',
  'dbpassword' => '!',
  'logtimezone' => 'UTC',
  'installed' => true,
  'appstore.experimental.enabled' => true,
  'theme' => '', 
'loglevel' => 2,
  'maintenance' => false,
  'trashbin_retention_obligation' => 'auto',
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'server.com',
  'mail_smtphost' => 'kierpaul.server',
  'mail_smtpport' => '465',
  'mail_smtpsecure' => 'tls',
  'updatechecker' => false,

```

### Client configuration
**Browser:**Firefox

**Operating system:**Linux Mint

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Horde log (data/horde.log)
```
Insert your horde log here, see https://github.com/owncloud/mail#debug-mode
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

Finally, this error comes up:

Signature could not get checked. Please contact the app developer and check your admin screen.

**Comment by Echse27** [comment] 2016-03-31 06:18
Same here:
Error: "Die Signatur konnte nicht überprüft werden. Bitte kontaktiere die App-Entwickler und überprüfe deinen Admin-Bildschirm."

**Comment by Gomez** [comment] 2016-03-31 06:32
I will try to reproduce later. Both installed from the app store? 

@LukasReschke You have a idea?

**Comment by Echse27** [comment] 2016-03-31 06:54
I have done an upgrade from 0.4.0 to 0.4.1 via the appstore inside owncloud...
Now i deleted the both mail databases, the mail app folder and the values inside the appconfig database for mail app...
Now i will wait for mail 0.4.1 stable
Why the hash of .htaccess will changed during the app upgrade? Because there a no changes inside the file...?

**Comment by LukasReschke** [comment] 2016-03-31 07:08
Please post the result of http://localhost/oc/settings/integrity/failed

>  Why the hash of .htaccess will changed during the app upgrade? Because there a no changes inside the file...?

This is fixed in 9.0.1.

**Comment by Echse27** [comment] 2016-03-31 07:11
Following the output of https://..../owncloud/index.php/settings/integrity/failed

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .htaccess

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => f40e7ca19cd76ff922ccd164e38f4d73806f66170cafa202fb470be225c813b4b242f4321da8a01bef1329e300acf3d137dbcbff058c501f166a2619031fc651
                            [current] => 9ca275edcff714265e0008ed1f02c8d588aa22a9e7e185fc83401f5ff0fb144aa7d3d658862ae5f682c1cf07235ad6856e55062c56c22b4acbf3dfa573b87420
                        )

                )

        )

)
```

**Comment by Lefuneste** [comment] 2016-04-01 02:14
On a fresh install of OC 9.0.0.19
Debian Jessie
Apache 2.4.10
PHP 5.6.17
MySQL server 5.5.47
when trying to install Mail 0.4.1 from the app list I get:
"Signature could not get checked. Please contact the app developer and check your admin screen."

Other approved apps did install flawlessly

Error log show http://.../owncloud/index.php/settings/integrity/failed

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- mail
	- FILE_MISSING
		- .bowerrc
		- .git/COMMIT_EDITMSG
		- .git/FETCH_HEAD
		- .git/HEAD
		- .git/ORIG_HEAD
		- .git/config
		- .git/description
		- .git/hooks/applypatch-msg.sample
		- .git/hooks/commit-msg.sample
		- .git/hooks/post-update.sample
		- .git/hooks/pre-applypatch.sample
		- .git/hooks/pre-commit.sample
		- .git/hooks/pre-push.sample
		- .git/hooks/pre-rebase.sample
		- .git/hooks/prepare-commit-msg.sample
		- .git/hooks/update.sample
		- .git/index
		- .git/info/exclude
		- .git/logs/HEAD
		- .git/logs/refs/heads/account-backbone-model
		- .git/logs/refs/heads/downgrade_backbone
		- .git/logs/refs/heads/fix-attachments
		- .git/logs/refs/heads/fix-service-resolution
		- .git/logs/refs/heads/folder-backbone-model
		- .git/logs/refs/heads/ignore-new-contact-images
		- .git/logs/refs/heads/master
		- .git/logs/refs/heads/new-message-view
		- .git/logs/refs/heads/replace-ihelper
		- .git/logs/refs/heads/reply-button-placement
		- .git/logs/refs/heads/setup-ux
		- .git/logs/refs/remotes/origin/HEAD
		- .git/logs/refs/remotes/origin/master
		- .git/logs/refs/remotes/origin/new-message-view
		- .git/logs/refs/remotes/origin/update-php-libs
		- .git/logs/refs/stash
		- .git/objects/00/9c9c62ab8feda92041530d98b387df28a0f279
		- .git/objects/01/9935b580b640378f74c7c926a100a033282b71
		- .git/objects/01/ee2e936c31dc8f49284fa6bc6ba344f78d188e
		- .git/objects/04/26249e0d820ae819f40eb61ab4faccc1120ae1
		- .git/objects/04/ca0f17b78338bec7e8ec1f76784de388567f1b
		- .git/objects/05/529fa606fa198a954cbabd513e60dad5b0a4e2
		- .git/objects/05/e47127362a3a93c6c58131c00abac255bb013d
		- .git/objects/07/10f23ea22302351ffc2503af0eb850718fd003
		- .git/objects/07/219412e12123704a09dac0c07a785ec5df3dc5
		- .git/objects/07/9a55f59e7514e9bdfba9a2acb78da76392737b
		- .git/objects/07/c6768d49c9762b4bb4d9697d1e7f6e32dfc8a1
		- .git/objects/08/177c78784bab7cf17d0c2cc6f078b5a50291d6
		- .git/objects/08/6f762e9b7b1b6fc4093de95f6a5b6d6cccf7e3
		- .git/objects/08/7893639755363bb14b0cc6c11553933bed1538
		- .git/objects/08/d3c1aefafa3d660c387080ec0c1631cdc3a1b1
		- .git/objects/09/43d16eb096f75fe263dd6dedc921c4626c3708
		- .git/objects/09/4fad4b9bd50cd9e4dcd7a3a04ff14c4305dba8
		- .git/objects/09/6ea1b58ac273e5be589c697992a250aeb50c2c
		- .git/objects/09/f2b462121c4fbc67e0ec36ae1f9132c8050434
		- .git/objects/0a/3443220ed6706d55a2006e8bc94e32c5555a31
		- .git/objects/0a/626b74efc6a45fd67f9a09e4e0615976462f81
		- .git/objects/0a/6bf167c01e8161b0812b96c44b089943ad9dff
		- .git/objects/0a/843e8fcc800a89d923a13c3a147ee2fc985a27
		- .git/objects/0b/4a0cfd27ee27179599fcc6177662fe88f465ba
		- .git/objects/0b/b12dba65a78be5f3aec626f262453158d68287
		- .git/objects/0b/ff3cc432cb03108f57faf29e30abc82bd2b1fa
		- .git/objects/0c/4bd9a2d5c5cbec54c8a25bb8c3b8b1b1437e92
		- .git/objects/0c/d74c2e6402fc60e4efc36b996b6d6724624f93
		- .git/objects/0d/5873a989f711a1af8f1e8fa8ed29e77b272e17
		- .git/objects/0d/ddd5c6f3467b1b693415ede61203f2dd98573a
		- .git/objects/0e/38a49a3ee5395cca129d638b515cd90cdc2695
		- .git/objects/0e/afae009d269edcdae1e9a02304112962b15ee4
		- .git/objects/0f/350608e2bc359688acf1e1190ea57c1885f9e0
		- .git/objects/11/03fc463a3c44baf374bb19656248735b6a18e4
		- .git/objects/12/1070a01c224119751acb531e580f0af31f117d
		- .git/objects/13/43ba3d7f05a4f1f134963b37a672d493a7cb7a
		- .git/objects/13/b82c4ba82cb86f477c70a84d364981c57bfc43
		- .git/objects/13/b9231f959287d55b5093936161417987ba92e9
		- .git/objects/14/143e02ca74aac7f2b3a3de85cbab7377fd8d8a
		- .git/objects/14/b4cd23ba4905a82758c41763ead31409911ca0
		- .git/objects/16/34c23ada9411be0ed0546bfa25b56722063fec
		- .git/objects/17/3bc3f80d4c6422a5654b68388169e0acc76ec6
		- .git/objects/17/a59c85391a5ae4d832fa635c3f822817aac197
		- .git/objects/18/1687706aec1a9fae44074093a8ece11a8c5bf7
		- .git/objects/18/280fb39bd5e0423fb8659a259fa36b89718af9
		- .git/objects/18/9e14b898f69952c83ad2e310282f17712491fe
		- .git/objects/1a/6bd57bbbf5a18b320a575ca4180c29717d3bb3
		- .git/objects/1a/a5788ce2981b8470daf5ee0e5159ecd62a3a3e
		- .git/objects/1a/bbe21fef213d0f2d96326432f292c698b0bf37
		- .git/objects/1b/c8a0f7bd9b012c02aba01330ce709ef24d6ca8
		- .git/objects/1c/9f511901e918c78c2b6597eb763c43d8d0eaad
		- .git/objects/1d/b269be967b490d7c6a48378d21a85882e455eb
		- .git/objects/20/1ed6b45592e23c3c09612d415338ea38bfe22a
		- .git/objects/20/42a47e98a765412e1be92697c305ffcc3c3062
		- .git/objects/20/8928544f537e686d7f37c4fb1347f22fb10a8f
		- .git/objects/20/d3977e56a6b7ddc2af1f85e758435e76482c5d

--> Followed by an atrociously long list of missing files until...	

            [INVALID_HASH] => Array
                (
                    [js/vendor/jquery/.bower.json] => Array
                        (
                            [expected] => 4c5c78424c2904a280e76b808e800723a31fa3545ee2b926f8e49142b4d967e8c39c0d1cef3cf3223e581379ca7fc6df4ef07349ad27b0e4c6ab47564c632ea1
                            [current] => f1d3cb37e8f423900a0c743dbdff599b4a97277f3a72e39d571422a49e9efebd90d741b21ff3a81ea1e4a61a428cbd2402cddcab31d9051f9642102c1c8aed46
                        )

                )

        )

)

**Comment by Lefuneste** [comment] 2016-04-01 02:31
I also get this error message in my apache error.log:

authz_core:error] [pid 11527] [client 127.0.0.1:48911] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata

.ocdata is an empty file

**Comment by ChristophWurst** [comment] 2016-04-01 06:17
@Gomez apparently you signed the raw app directory, not the packaged app. Please run ``make appstore``, untar the archive and sign that directory.

**Comment by ChristophWurst** [comment] 2016-04-01 06:18
@LukasReschke do we have to increase the app version when re-uploading the app to the appstore?

**Comment by LukasReschke** [comment] 2016-04-01 06:25
@ChristophWurst You don't technically need to. But it's good practise.

**Comment by Gomez** [comment] 2016-04-01 07:34
Arg, fixed now. I uploaded the new tar.gz. How do i need to test it? I does not get a error...

**Comment by Gomez** [comment] 2016-04-01 07:35
@joe-liberty @Echse27 @Lefuneste Would you pls retry to install.

**Comment by Echse27** [comment] 2016-04-01 07:41
@Gomez 
thanks... it seems to work now
No error or warning message...

but now, what´s up with the hash of my .htaccess while integrity check?

**Comment by ChristophWurst** [comment] 2016-04-01 07:47
@Echse27 that has been fixed by @LukasReschke. See https://github.com/owncloud/core/pull/23250

**Comment by ChristophWurst** [comment] 2016-04-01 07:48
@Gomez I just re-installed the app on my production system and integrity checks pass now. Thanks

**Closed by ChristophWurst** 2016-04-01 07:48 UTC
Labels: 1 - to develop, bug, priority

**Comment by Echse27** [comment] 2016-04-01 07:56
@ChristophWurst 
Thie (owncloud/core#23250) means, i have to install php7... ???

**Comment by ChristophWurst** [comment] 2016-04-01 08:00
@Echse27 no, that PR excludes custom changes to the .htaccess file when running the integrity check.

**Comment by Echse27** [comment] 2016-04-01 08:08
Ok, but i don't know what i have to do to fix the error for the hash of the
.htaccess
Am 01.04.2016 10:00 schrieb "Christoph Wurst" <notifications@github.com>:

**Comment by Lefuneste** [comment] 2016-04-01 20:15
@Gomez To confirm, I've tried reinstalling without doing any change and it worked perfectly !! Thanks !!

**Comment by joe-liberty** [comment] 2016-04-01 21:23
@Gomez I reinstalled today and it is working fine. Thank you, we will mark this solved!
