### ISSUE TITLE
Wrong link detection

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#841] opened 2015-07-03 07:07 UTC
Non-HTML mails like the following cause problems:
```
Hi,
bla bla: http://example.com/

lorem ipsum (http://test.at/)
regards
```
This is shown as:
```HTML

			
			Hi,<br>
bla bla: <a href="http://example.com/<br ></a>
<br />
lorem" target="_blank" rel="noreferrer">http://example.com/<br>
<br>
lorem</a> ipsum (<a href="http://test.at/)<br ></a>
regards<br />
<br />
" target="_blank" rel="noreferrer">http://test.at/)<br>
regards<br>
<br>
</a>
			
		
```

**Comment by DeepDiver1975** [comment] 2015-07-03 07:48
caused by this https://github.com/owncloud/mail/pull/823

**Comment by jancborchardt** [comment] 2015-07-03 09:53
Similar here for this URL:
https://github.com/owncloud/core/pulls?page=3&q=is%3Aopen+is%3Apr+label%3A%223+-+To+Review%22&utf8=%E2%9C%93

Only this part is linkified:
https://github.com/owncloud/core/pulls?page=3

**Comment by clementhk** [comment] 2015-07-03 10:12
It would be cool to continue the discussion in #641 and find the best solution.
As far as I see it, we should consider following options.
1. Find a ready and tested php version.
2. Use linkifyjs as @Xenopathic suggested.
3. Translate linkifyjs into php to not use regex and use such everyone can maintain solution https://github.com/SoapBox/linkifyjs/blob/master/src/linkify/core/scanner.js

**Comment by clementhk** [comment] 2015-07-03 11:05
https://bitbucket.org/kwi/urllinker/src

**Comment by DeepDiver1975** [comment] 2015-07-03 11:07
> https://bitbucket.org/kwi/urllinker/src

Nice - thanks for the pointer!

**Comment by DeepDiver1975** [comment] 2015-07-03 11:07
We should really give it a try. PRs welcome!

**Comment by DeepDiver1975** [comment] 2015-07-06 14:43
> https://bitbucket.org/kwi/urllinker/src

not available via composer .... seems dead

**Comment by Xenopathic** [comment] 2015-07-06 18:31
IMHO stuff like this should be done client side, to reduce load on the server. No so important on a dual CPU Xeon with 128GB of RAM, but a Raspberry Pi will be much happier if it doesn't have to do the linkifying :smile:

**Comment by clementhk** [comment] 2015-07-07 00:40
@Xenopathic I always believe the opposite, load should be on server and client should be as light as possible.
About composer, it seems like the link was not committed by the author, but from @MacDada , so I think think it has ever been into composer.
In any case we might need a modified version for mailto:(?), and as far as I can talk, there's no major issue been reported.

**Comment by MacDada** [comment] 2015-07-07 13:37
Yeah, I made `kwi/urlinker` PSR–friendly and I know there are some issues, but I don't really have time to look into that right now – please wait for the weekend ;-)

**Comment by DeepDiver1975** [comment] 2015-07-07 14:05
> please wait for the weekend ;-)

This awesome! Thanks a lot @MacDada - let us know as soon as you are done - THX

**Comment by MacDada** [comment] 2015-07-13 08:25
@DeepDiver1975 It should be working now: https://bitbucket.org/kwi/urllinker/issues/14/composer-support#comment-20046865

**Closed** 2015-07-15 14:38 UTC
Labels: 1 - to develop, bug
