### ISSUE TITLE
drafts contains no body

### ISSUE THREAD

**Issue by guidovanharten** [owncloud/mail#1174] opened 2015-11-27 08:04 UTC
When I've composed a mail and wouldn't send it, I leave the composer window and i.e. click on Inbox or I close the tab in my browser, the mail which is saved into the Drafts folder of that mailbox only contains the sender and the recipient's name. There is no mail body.

**Comment by ChristophWurst** [comment] 2015-11-27 08:07
Thanks for reporting. Which version of the mail app is used? How many accounts are used?

**Comment by guidovanharten** [comment] 2015-11-27 08:22
I am surprised: when I go to the tab Apps and scroll to the enabled apps I see that the app Mail is experimental. I am sure (ok, 99.9%) that it wasn't experimental when I installed the app.
I have 5 mailaccounts.

Regards,
Guido

**Comment by ChristophWurst** [comment] 2015-11-27 08:25
So, which version is installed on your system? 0.2.1 from the app store?

**Comment by guidovanharten** [comment] 2015-11-27 08:33
I am sorry that I didn't wrote it :(
Yes, it is 0.2.1.

**Comment by Gomez** [comment] 2015-11-27 09:57
Works for me in 0.3 with #1173 branch. 
As soon as we merge this, this can be tested again. @guidovanharten We will ping you

**Comment by ChristophWurst** [comment] 2015-12-24 10:42
#1173 has been merged. @guidovanharten could you try a [nightly build](https://github.com/owncloud/mail#nightly-builds) and check if the issue is resolved? Thanks.

**Comment by ChristophWurst** [comment] 2016-01-02 17:38
@guidovanharten ping

**Comment by guidovanharten** [comment] 2016-01-02 18:17
I am sorry for the delay. I am installing the today build now. The first test was succesfull. The text of my - very short - first test mail was save correct in the Drafts folder.

**Comment by ChristophWurst** [comment] 2016-01-06 20:31
I assume the error is resolved. If not, please re-open the issue, thanks.

**Closed by ChristophWurst** 2016-01-06 20:31 UTC
Labels: 1 - to develop, bug, needs info
