### ISSUE TITLE
Interprets links with parameters incorrectly

### ISSUE THREAD

**Issue by sndrsk** [owncloud/mail#1071] opened 2015-09-13 04:01 UTC
On Mail 0.2, I've had this happen a couple of times now, the first time I thought it was just a fluke from the sender. This time I received a password reset request for a forum.

- oC Mail displayed the link as: forum.tld/forum/login.php&u=15192&i=b4987f9f357f9506761285c2b452cff6ea3d3aff
- The clickable portion of the link took me to: http://forum.tld/forum/login.php?a=pwd and only the forum.tld/forum/login.php was clickable
- The actual link as written by the sender was http://forum.tld/forum/login.php?a=pwd&u=15192&i=b4987f9f357f9506761285c2b452cff6ea3d3aff

So it looked like this: `<a href="http://forum.tld/forum/login.php?a=pwd">forum.tld/forum/login.php</a>&u=15192&i=b4987f9f357f9506761285c2b452cff6ea3d3aff`

**Comment by sndrsk** [comment] 2015-10-13 00:37
As I'm browsing issues, could this be related to #930?

**Comment by jancborchardt** [comment] 2015-11-05 15:07
@sndrsk yeah – sorry for the late reply but yes, this is basically a duplicate of https://github.com/owncloud/mail/issues/930 – I changed the title there accordingly.

Could you add the problems you were facing in there? And it would be cool if you can dive in and try how to fix it. :)

**Closed by jancborchardt** 2015-11-05 15:07 UTC
Labels: 1 - to develop, bug, priority

**Comment by sndrsk** [comment] 2015-11-11 00:06
I'm heading on over to #930. I would love to help and fix/develop things for ownCloud but unfortunately my coding expertise is limited to copying/pasting and literally messing with things all night until I get it to make a very minor aesthetic modification!

**Comment by jancborchardt** [comment] 2015-11-11 07:54
@sndrsk testing, finding and reporting issues is always appreciated as well. :)
