### ISSUE TITLE
ownCloud 9.0: no contact-autocomplete

### ISSUE THREAD

**Issue by BenS89** [owncloud/mail#1361] opened 2016-03-21 17:31 UTC
### Steps to reproduce
1. Upgrade from mail 0.3.0 to 0.4.0
2. Consider [#1352](https://github.com/owncloud/mail/pull/1352) (fix for [#1337](https://github.com/owncloud/mail/issues/1337))
3. Have contacts app 1.0.0 installed with some contacts 
4. Create a new email 
5. Type in some letters in the "to"-field

### Expected behaviour
There is an autocomplete-mechanism that displays matching contacts from the contacts-app

### Actual behaviour
Nothing happens. The user has to type in the full mail-address manually. 

**OwnCloud Mail version:** (see ownCloud apps admin page)  0.4.0

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...) iCloud

**Number of accounts:** 1

### Server configuration
**Operating system**: Qnap Embedded Linux

**Web server:** Apache 2.4.12

**Database:** MariaDB 5.5

**PHP version:** 5.6

**ownCloud version:** (see ownCloud admin page) 9.0

**Updated from an older ownCloud or fresh install:** yes, from 8.2.2

**List of activated apps:** Calendar 1.0, Contacts 1.0, Mail 0.4.0

**Comment by ChristophWurst** [comment] 2016-03-21 18:38
Duplicate of #1345

**Closed by ChristophWurst** 2016-03-21 18:38 UTC
