### ISSUE TITLE
Could not resolve request! Class request does not exist

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/mail#1217] opened 2016-01-13 16:01 UTC
````


{
  "reqId": "UdTb+hA9UkNHTHv5C0Cx",
  "remoteAddr": "188.194.67.114",
  "app": "index",
  "message": "Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve request! Class request does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(106): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('request')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(66): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('request')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(85): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->buildClass(Object(ReflectionClass))\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(106): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\Mail\\\\\\\\Contro...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(96): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\Mail\\\\\\\\Contro...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('MessagesControl...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#6 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(291): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(849): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#9 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php\",\"Line\":91}",
  "level": 3,
  "time": "2016-01-13T15:59:59+00:00",
  "method": "GET",
  "url": "\/index.php\/apps\/mail\/accounts\/-1\/folders\/........"
}

**Comment by ChristophWurst** [comment] 2016-01-13 16:14
duplicate of #1207 ;-)

**Closed by ChristophWurst** 2016-01-13 16:14 UTC
