### ISSUE TITLE
Cant directly open images of plain text 

### ISSUE THREAD

**Issue by Gomez** [owncloud/mail#886] opened 2015-07-17 08:05 UTC
Got a mail with a photo attached. To open it, i need to move it to my cloud or download it local. 
Would be good if i can open it directly or get a scaled preview at the end of the mail?

**Comment by jancborchardt** [comment] 2015-07-17 08:43
Duplicate of https://github.com/owncloud/mail/issues/84 ;)

**Comment by jancborchardt** [comment] 2015-07-17 08:43
Also – pull request please! :D

**Closed by jancborchardt** 2015-07-17 08:43 UTC
