### ISSUE TITLE
When opening the composer, the currently active account should be selected automatically

### ISSUE THREAD

**Issue by wurstchristoph** [owncloud/mail#725] opened 2015-05-25 22:38 UTC
ATM the very first account is preselected in the composer. I would say it makes more sense to preselect the currently active account.

Steps to reproduce:
- Open folder of a mail account other than your very first one
- Click 'New message'
- The first account is selected instead of the currently active one

**Comment by jancborchardt** [comment] 2015-05-26 17:53
I could have sworn we have an existing issue for this ... fully agree for sure. ;)

**Comment by jancborchardt** [comment] 2015-05-26 17:54
There it is - duplicate of https://github.com/owncloud/mail/issues/297 :)

**Closed by jancborchardt** 2015-05-26 17:54 UTC
Labels: 1 - to develop, enhancement, priority, starter issue
